/**
 * MEDINA Sandbox Orchestrator
 *
 * The organism's immune system for external access. Manages gated clones per
 * tier, ensuring that external consumers only ever interact with a controlled
 * projection of the sovereign state — never the living interior.
 *
 * Tiers range from PUBLIC (most open) to SOVEREIGN (most protected). Each
 * sandbox session is assigned a gate level that determines the fidelity of the
 * data surface returned. Unauthorized access receives a mirage — a plausible
 * but content-free response designed to reveal structure without leaking truth.
 *
 * @module sandboxOrchestrator
 */

import { sovereignId } from './sovereign-id';

// ─── Types ──────────────────────────────────────────────────────────────────

export type SandboxTier =
  | 'PUBLIC'
  | 'ENTERPRISE'
  | 'PARTNER'
  | 'INTERNAL'
  | 'SOVEREIGN';

export type GateLevel =
  | 'OPEN'
  | 'PARTIAL'
  | 'OBSCURED'
  | 'SEALED'
  | 'PROTECTED';

export interface AccessLogEntry {
  id: string;
  resource: string;
  gateLevel: GateLevel;
  timestamp: string;
  allowed: boolean;
}

export interface SandboxSession {
  id: string;
  tier: SandboxTier;
  gateLevel: GateLevel;
  requesterId: string;
  createdAt: string;
  expiresAt: string;
  accessLog: AccessLogEntry[];
}

export interface MirageResponse {
  kind: 'mirage';
  resource: string;
  structure: Record<string, string>;
  notice: string;
  generatedAt: string;
}

export interface GatedAccessResult {
  sessionId: string;
  resource: string;
  gateLevel: GateLevel;
  data: Record<string, unknown> | MirageResponse;
  allowed: boolean;
}

export interface SandboxStats {
  totalSessions: number;
  activeSessions: number;
  expiredSessions: number;
  byTier: Record<SandboxTier, number>;
  totalAccessAttempts: number;
}

// ─── Constants ──────────────────────────────────────────────────────────────

const TIER_ORDER: SandboxTier[] = [
  'PUBLIC',
  'ENTERPRISE',
  'PARTNER',
  'INTERNAL',
  'SOVEREIGN',
];

const DEFAULT_GATE_LEVELS: Record<SandboxTier, GateLevel> = {
  PUBLIC: 'OBSCURED',
  ENTERPRISE: 'PARTIAL',
  PARTNER: 'PARTIAL',
  INTERNAL: 'OPEN',
  SOVEREIGN: 'OPEN',
};

const SESSION_TTL_MS: Record<SandboxTier, number> = {
  PUBLIC: 15 * 60 * 1000,
  ENTERPRISE: 60 * 60 * 1000,
  PARTNER: 60 * 60 * 1000,
  INTERNAL: 4 * 60 * 60 * 1000,
  SOVEREIGN: 24 * 60 * 60 * 1000,
};

// ─── State ──────────────────────────────────────────────────────────────────

const sessions: Map<string, SandboxSession> = new Map();

// ─── Helpers ────────────────────────────────────────────────────────────────

function isSessionExpired(session: SandboxSession): boolean {
  return new Date(session.expiresAt).getTime() < Date.now();
}

function tierIndex(tier: SandboxTier): number {
  return TIER_ORDER.indexOf(tier);
}

function redactValue(key: string): string {
  return `[REDACTED:${key}]`;
}

function obscureValue(key: string): string {
  return `███ (${key.length} chars)`;
}

// ─── Mirage Generator ───────────────────────────────────────────────────────

/**
 * Generates a plausible but content-free response for unauthorized access.
 * The mirage preserves structural shape so callers see a believable schema
 * without receiving any real data.
 */
export function generateMirage(resource: string): MirageResponse {
  const placeholders: Record<string, string> = {
    id: sovereignId(),
    name: redactValue('name'),
    status: 'unknown',
    value: obscureValue('value'),
    description: 'This resource is not available at your access tier.',
    owner: redactValue('owner'),
    createdAt: new Date(0).toISOString(),
    updatedAt: new Date(0).toISOString(),
  };

  return {
    kind: 'mirage',
    resource,
    structure: placeholders,
    notice: 'Response generated by MEDINA mirage layer. No real data is included.',
    generatedAt: new Date().toISOString(),
  };
}

// ─── Gate Resolution ────────────────────────────────────────────────────────

function applyGate(
  resource: string,
  data: Record<string, unknown>,
  gateLevel: GateLevel,
): Record<string, unknown> | MirageResponse {
  switch (gateLevel) {
    case 'OPEN':
      return { ...data };

    case 'PARTIAL': {
      const filtered: Record<string, unknown> = {};
      for (const [key, val] of Object.entries(data)) {
        filtered[key] = typeof val === 'string' && val.length > 20
          ? redactValue(key)
          : val;
      }
      return filtered;
    }

    case 'OBSCURED': {
      const obscured: Record<string, unknown> = {};
      for (const key of Object.keys(data)) {
        obscured[key] = obscureValue(key);
      }
      return obscured;
    }

    case 'SEALED':
      return {
        _meta: true,
        resource,
        fieldCount: Object.keys(data).length,
        notice: 'Sealed tier — only metadata returned.',
      };

    case 'PROTECTED':
      return generateMirage(resource);
  }
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Opens a gated sandbox session for the given tier and requester.
 */
export function createSandboxSession(
  tier: SandboxTier,
  requesterId: string,
): SandboxSession {
  const now = new Date();
  const session: SandboxSession = {
    id: sovereignId(),
    tier,
    gateLevel: DEFAULT_GATE_LEVELS[tier],
    requesterId,
    createdAt: now.toISOString(),
    expiresAt: new Date(now.getTime() + SESSION_TTL_MS[tier]).toISOString(),
    accessLog: [],
  };
  sessions.set(session.id, session);
  return session;
}

/**
 * Resolves access to a resource within a sandbox session.
 * Returns the gated clone of the data or a mirage for unauthorized access.
 */
export function resolveAccess(
  sessionId: string,
  resource: string,
  data: Record<string, unknown> = {},
): GatedAccessResult {
  const session = sessions.get(sessionId);

  if (!session || isSessionExpired(session)) {
    const mirage = generateMirage(resource);
    return {
      sessionId,
      resource,
      gateLevel: 'PROTECTED',
      data: mirage,
      allowed: false,
    };
  }

  const result = applyGate(resource, data, session.gateLevel);
  const allowed = session.gateLevel !== 'PROTECTED';

  const logEntry: AccessLogEntry = {
    id: sovereignId(),
    resource,
    gateLevel: session.gateLevel,
    timestamp: new Date().toISOString(),
    allowed,
  };
  session.accessLog.push(logEntry);

  return {
    sessionId: session.id,
    resource,
    gateLevel: session.gateLevel,
    data: result,
    allowed,
  };
}

/**
 * Lists all active (non-expired) sandbox sessions.
 */
export function listSessions(): SandboxSession[] {
  return Array.from(sessions.values()).filter((s) => !isSessionExpired(s));
}

/**
 * Requests tier escalation for an existing session.
 * The new tier must be more protected (higher index) than the current tier.
 * Returns the updated session or null if the escalation is invalid.
 */
export function escalateTier(
  sessionId: string,
  newTier: SandboxTier,
): SandboxSession | null {
  const session = sessions.get(sessionId);
  if (!session || isSessionExpired(session)) return null;

  if (tierIndex(newTier) <= tierIndex(session.tier)) return null;

  const updated: SandboxSession = {
    ...session,
    tier: newTier,
    gateLevel: DEFAULT_GATE_LEVELS[newTier],
  };
  sessions.set(sessionId, updated);
  return updated;
}

/**
 * Returns aggregate stats for all sandbox sessions.
 */
export function getSandboxStats(): SandboxStats {
  const all = Array.from(sessions.values());
  const active = all.filter((s) => !isSessionExpired(s));
  const expired = all.filter((s) => isSessionExpired(s));

  const byTier: Record<SandboxTier, number> = {
    PUBLIC: 0,
    ENTERPRISE: 0,
    PARTNER: 0,
    INTERNAL: 0,
    SOVEREIGN: 0,
  };
  for (const s of active) {
    byTier[s.tier]++;
  }

  const totalAccessAttempts = all.reduce(
    (sum, s) => sum + s.accessLog.length,
    0,
  );

  return {
    totalSessions: all.length,
    activeSessions: active.length,
    expiredSessions: expired.length,
    byTier,
    totalAccessAttempts,
  };
}
