/**
 * Token Factory — ICRC / ERC token canister & contract scaffolds
 */

import { sovereignId } from '@/lib/sovereign-id';
import type { GeneratedFile, TokenSpec } from '@/types/appBuilder';

export function generateICRC1Canister(spec: TokenSpec): GeneratedFile[] {
  const actorName = spec.symbol.replace(/\W/g, '') || 'Token';

  return [{
    path: `icp/token/${spec.symbol.toLowerCase()}_token.mo`,
    language: 'motoko',
    content: `// ICRC-1 Token: ${spec.name} (${spec.symbol})
// Generated by MEDINA Token Factory

import Nat "mo:base/Nat";
import Text "mo:base/Text";
import HashMap "mo:base/HashMap";

actor class ${actorName}Token(initialSupply: Nat) {
  type Account = { owner: Principal; subaccount: ?Blob };

  stable var name: Text = "${spec.name}";
  stable var symbol: Text = "${spec.symbol}";
  stable var decimals: Nat8 = ${spec.decimals};
  stable var totalSupply: Nat = initialSupply;

  var balances = HashMap.HashMap<Principal, Nat>(100, Principal.equal, Principal.hash);

  public query func icrc1_name() : async Text { name };
  public query func icrc1_symbol() : async Text { symbol };
  public query func icrc1_decimals() : async Nat8 { decimals };
  public query func icrc1_total_supply() : async Nat { totalSupply };

  public shared(msg) func icrc1_transfer(args: {
    from_subaccount: ?Blob;
    to: Account;
    amount: Nat;
    fee: ?Nat;
    memo: ?Blob;
    created_at_time: ?Nat64;
  }) : async { #Ok : Nat; #Err : Text } {
    // Transfer logic — wire ledger in production
    #Ok(0)
  };
};
`,
  }, {
    path: `icp/token/${spec.symbol.toLowerCase()}_deploy.json`,
    language: 'json',
    content: JSON.stringify({
      canister: `${spec.symbol.toLowerCase()}_token`,
      init_arg: [spec.initialSupply],
      network: 'ic',
      standard: spec.standard,
    }, null, 2),
  }];
}

export function generateERC20Contract(spec: TokenSpec): GeneratedFile[] {
  return [{
    path: `contracts/${spec.symbol}Token.sol`,
    language: 'solidity',
    content: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract ${spec.symbol}Token is ERC20 {
    constructor() ERC20("${spec.name}", "${spec.symbol}") {
        _mint(msg.sender, ${spec.initialSupply} * 10 ** ${spec.decimals});
    }
}
`,
  }];
}

export function createTokenArtifacts(spec: TokenSpec): { files: GeneratedFile[]; tokenId: string } {
  const tokenId = sovereignId();
  let files: GeneratedFile[] = [];
  if (spec.standard === 'ICRC-1' || spec.standard === 'ICRC-7') {
    files = generateICRC1Canister(spec);
  } else {
    files = generateERC20Contract(spec);
  }
  files.push({
    path: 'token/manifest.json',
    language: 'json',
    content: JSON.stringify({ id: tokenId, ...spec, createdAt: new Date().toISOString() }, null, 2),
  });
  return { files, tokenId };
}
