/**
 * 𓂀 ALL BACKEND TOOLS AS MODELS - NOW 𓂀
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * EVERY backend tool - ALL NOW
 * Each tool = Model with 5 intelligences and multiple uses
 * These are AGENTS that can be USED
 * 
 * NOT FUTURE - NOW
 * 
 * @version 1.1.2 (Fibonacci)
 * @designation (NEXUS-BE-TOOLS)
 */

// ═══════════════════════════════════════════════════════════════════════════════
// DATABASE TOOLS (20 Tools)
// ═══════════════════════════════════════════════════════════════════════════════

export const DATABASE_TOOLS = [
  { id: 'db_1', name: 'PostgreSQL', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'QueryAgent',purpose:'Execute queries'},{id:'a2',name:'IndexAgent',purpose:'Manage indexes'},{id:'a3',name:'ReplicationAgent',purpose:'Handle replication'},{id:'a4',name:'OptimizeAgent',purpose:'Query optimization'},{id:'a5',name:'BackupAgent',purpose:'Backup/restore'}], uses: ['ACID transactions', 'Complex queries', 'JSON support', 'Full-text search', 'Geospatial', 'Extensions', 'Replication', 'Partitioning', 'Analytics', 'Enterprise'], frequency: 963, always_running: true },
  { id: 'db_2', name: 'MySQL', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'QueryAgent',purpose:'Queries'},{id:'a2',name:'IndexAgent',purpose:'Indexes'},{id:'a3',name:'ReplicationAgent',purpose:'Replication'},{id:'a4',name:'ClusterAgent',purpose:'Clustering'},{id:'a5',name:'BackupAgent',purpose:'Backup'}], uses: ['Web applications', 'E-commerce', 'Data warehousing', 'Logging', 'Replication', 'Clustering', 'Performance', 'Security', 'Stored procedures', 'Triggers'], frequency: 852, always_running: true },
  { id: 'db_3', name: 'MongoDB', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'DocumentAgent',purpose:'Document operations'},{id:'a2',name:'AggregateAgent',purpose:'Aggregation'},{id:'a3',name:'IndexAgent',purpose:'Indexing'},{id:'a4',name:'ShardAgent',purpose:'Sharding'},{id:'a5',name:'ReplicaAgent',purpose:'Replica sets'}], uses: ['Document storage', 'Flexible schema', 'Aggregation', 'Geospatial', 'Time series', 'Search', 'Sharding', 'Replica sets', 'Change streams', 'Transactions'], frequency: 852, always_running: true },
  { id: 'db_4', name: 'Redis', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'CacheAgent',purpose:'Caching'},{id:'a2',name:'PubSubAgent',purpose:'Pub/Sub'},{id:'a3',name:'StreamAgent',purpose:'Streams'},{id:'a4',name:'LuaAgent',purpose:'Lua scripts'},{id:'a5',name:'ClusterAgent',purpose:'Clustering'}], uses: ['Caching', 'Session storage', 'Real-time analytics', 'Pub/Sub', 'Queues', 'Rate limiting', 'Leaderboards', 'Geospatial', 'Streams', 'Lua scripting'], frequency: 963, always_running: true },
  { id: 'db_5', name: 'Elasticsearch', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'SearchAgent',purpose:'Full-text search'},{id:'a2',name:'IndexAgent',purpose:'Indexing'},{id:'a3',name:'AggregateAgent',purpose:'Aggregations'},{id:'a4',name:'ClusterAgent',purpose:'Clustering'},{id:'a5',name:'MonitorAgent',purpose:'Monitoring'}], uses: ['Full-text search', 'Log analysis', 'Analytics', 'Application search', 'Security analytics', 'Metrics', 'APM', 'SIEM', 'Geospatial', 'Machine learning'], frequency: 852, always_running: true },
  { id: 'db_6', name: 'Cassandra', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'PartitionAgent',purpose:'Partitioning'},{id:'a2',name:'ReplicationAgent',purpose:'Replication'},{id:'a3',name:'ConsistencyAgent',purpose:'Consistency'},{id:'a4',name:'CompactionAgent',purpose:'Compaction'},{id:'a5',name:'RepairAgent',purpose:'Repair'}], uses: ['Time series', 'IoT data', 'High availability', 'Global distribution', 'Wide column', 'Messaging', 'Logging', 'Analytics', 'Catalog', 'Recommendations'], frequency: 741, always_running: true },
  { id: 'db_7', name: 'DynamoDB', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'TableAgent',purpose:'Table management'},{id:'a2',name:'StreamAgent',purpose:'Streams'},{id:'a3',name:'IndexAgent',purpose:'Indexes'},{id:'a4',name:'TTLAgent',purpose:'TTL management'},{id:'a5',name:'BackupAgent',purpose:'Backup'}], uses: ['Serverless apps', 'Gaming', 'IoT', 'Mobile apps', 'Session management', 'Streams', 'Global tables', 'Auto scaling', 'Transactions', 'DAX caching'], frequency: 852, always_running: true },
  { id: 'db_8', name: 'SQLite', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'FileAgent',purpose:'File management'},{id:'a2',name:'QueryAgent',purpose:'Queries'},{id:'a3',name:'TransactionAgent',purpose:'Transactions'},{id:'a4',name:'VFSAgent',purpose:'Virtual file system'},{id:'a5',name:'ExtensionAgent',purpose:'Extensions'}], uses: ['Embedded database', 'Mobile apps', 'Desktop apps', 'Testing', 'Prototyping', 'Edge computing', 'Cache', 'Configuration', 'Logging', 'Temporary storage'], frequency: 639, always_running: true },
  { id: 'db_9', name: 'Neo4j', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'GraphAgent',purpose:'Graph operations'},{id:'a2',name:'CypherAgent',purpose:'Cypher queries'},{id:'a3',name:'AlgorithmAgent',purpose:'Graph algorithms'},{id:'a4',name:'IndexAgent',purpose:'Indexing'},{id:'a5',name:'ClusterAgent',purpose:'Clustering'}], uses: ['Graph database', 'Knowledge graphs', 'Fraud detection', 'Recommendations', 'Network analysis', 'Identity management', 'Supply chain', 'Social networks', 'Path finding', 'Impact analysis'], frequency: 741, always_running: true },
  { id: 'db_10', name: 'CockroachDB', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'DistributeAgent',purpose:'Distribution'},{id:'a2',name:'SurviveAgent',purpose:'Survivability'},{id:'a3',name:'ScaleAgent',purpose:'Scaling'},{id:'a4',name:'SQLAgent',purpose:'SQL compatibility'},{id:'a5',name:'GeoAgent',purpose:'Geo-partitioning'}], uses: ['Distributed SQL', 'Global apps', 'Resilience', 'Cloud native', 'Multi-region', 'Serializable isolation', 'Auto-rebalancing', 'Survivability', 'Online schema changes', 'Point-in-time recovery'], frequency: 852, always_running: true },
  // Continue with 10 more database tools...
  { id: 'db_11', name: 'ClickHouse', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'ColumnAgent',purpose:'Column storage'},{id:'a2',name:'QueryAgent',purpose:'OLAP queries'},{id:'a3',name:'MergeAgent',purpose:'Merge tree'},{id:'a4',name:'DistributeAgent',purpose:'Distribution'},{id:'a5',name:'MaterializeAgent',purpose:'Materialized views'}], uses: ['Analytics', 'OLAP', 'Time series', 'Log analysis', 'Real-time reporting', 'Data warehousing', 'IoT', 'Financial data', 'Web analytics', 'Monitoring'], frequency: 852, always_running: true },
  { id: 'db_12', name: 'TimescaleDB', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'TimeAgent',purpose:'Time series'},{id:'a2',name:'ChunkAgent',purpose:'Chunking'},{id:'a3',name:'CompressAgent',purpose:'Compression'},{id:'a4',name:'PolicyAgent',purpose:'Retention policies'},{id:'a5',name:'ContinuousAgent',purpose:'Continuous aggregates'}], uses: ['Time series', 'IoT', 'Monitoring', 'Analytics', 'Financial data', 'DevOps', 'Geospatial', 'Machine learning', 'Event data', 'Sensor data'], frequency: 741, always_running: true },
  { id: 'db_13', name: 'InfluxDB', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'WriteAgent',purpose:'High-speed writes'},{id:'a2',name:'QueryAgent',purpose:'Flux queries'},{id:'a3',name:'RetentionAgent',purpose:'Retention'},{id:'a4',name:'TaskAgent',purpose:'Tasks'},{id:'a5',name:'AlertAgent',purpose:'Alerting'}], uses: ['Time series', 'Monitoring', 'IoT', 'Real-time analytics', 'DevOps metrics', 'Sensor data', 'APM', 'Network monitoring', 'Industrial IoT', 'Financial ticks'], frequency: 741, always_running: true },
  { id: 'db_14', name: 'Vitess', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'ShardAgent',purpose:'Sharding'},{id:'a2',name:'VtGateAgent',purpose:'Query routing'},{id:'a3',name:'VtTabletAgent',purpose:'Tablets'},{id:'a4',name:'TopoAgent',purpose:'Topology'},{id:'a5',name:'VReplicationAgent',purpose:'VReplication'}], uses: ['MySQL scaling', 'Horizontal sharding', 'Online DDL', 'Resharding', 'Kubernetes native', 'Connection pooling', 'Query routing', 'Failover', 'Backup', 'Recovery'], frequency: 741, always_running: true },
  { id: 'db_15', name: 'PlanetScale', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'BranchAgent',purpose:'Branching'},{id:'a2',name:'SchemaAgent',purpose:'Schema changes'},{id:'a3',name:'ScaleAgent',purpose:'Scaling'},{id:'a4',name:'InsightAgent',purpose:'Insights'},{id:'a5',name:'BoostAgent',purpose:'Boost'}], uses: ['Serverless MySQL', 'Database branching', 'Non-blocking schema', 'Global distribution', 'Auto-scaling', 'Insights', 'Connections', 'Boost caching', 'Dev/prod parity', 'Git-like workflow'], frequency: 852, always_running: true },
  { id: 'db_16', name: 'Supabase', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'PostgresAgent',purpose:'Postgres'},{id:'a2',name:'AuthAgent',purpose:'Authentication'},{id:'a3',name:'StorageAgent',purpose:'Storage'},{id:'a4',name:'RealtimeAgent',purpose:'Real-time'},{id:'a5',name:'EdgeAgent',purpose:'Edge functions'}], uses: ['Firebase alternative', 'Auth', 'Database', 'Storage', 'Real-time', 'Edge functions', 'REST API', 'GraphQL', 'Row level security', 'Postgres extensions'], frequency: 852, always_running: true },
  { id: 'db_17', name: 'Prisma', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'ClientAgent',purpose:'Type-safe client'},{id:'a2',name:'MigrateAgent',purpose:'Migrations'},{id:'a3',name:'StudioAgent',purpose:'Studio'},{id:'a4',name:'SchemaAgent',purpose:'Schema'},{id:'a5',name:'AccelerateAgent',purpose:'Accelerate'}], uses: ['ORM', 'Type-safe queries', 'Migrations', 'Database GUI', 'Schema management', 'Query builder', 'Connection pooling', 'Edge deployment', 'Multiple databases', 'TypeScript'], frequency: 852, always_running: true },
  { id: 'db_18', name: 'Drizzle', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'QueryAgent',purpose:'Query builder'},{id:'a2',name:'SchemaAgent',purpose:'Schema'},{id:'a3',name:'MigrateAgent',purpose:'Migrations'},{id:'a4',name:'StudioAgent',purpose:'Studio'},{id:'a5',name:'KitAgent',purpose:'Kit'}], uses: ['TypeScript ORM', 'SQL-like syntax', 'Lightweight', 'Serverless ready', 'Edge ready', 'Multiple dialects', 'Migrations', 'Studio', 'Type safety', 'Performance'], frequency: 741, always_running: true },
  { id: 'db_19', name: 'Kysely', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'QueryAgent',purpose:'Query builder'},{id:'a2',name:'TypeAgent',purpose:'Type inference'},{id:'a3',name:'DialectAgent',purpose:'Dialects'},{id:'a4',name:'MigrateAgent',purpose:'Migrations'},{id:'a5',name:'PluginAgent',purpose:'Plugins'}], uses: ['Type-safe SQL', 'Query builder', 'TypeScript', 'PostgreSQL', 'MySQL', 'SQLite', 'Migrations', 'Code generation', 'Minimal overhead', 'Composable'], frequency: 639, always_running: true },
  { id: 'db_20', name: 'TypeORM', type: 'DATABASE', intelligences: 5, agents: [{id:'a1',name:'EntityAgent',purpose:'Entities'},{id:'a2',name:'RelationAgent',purpose:'Relations'},{id:'a3',name:'QueryAgent',purpose:'Query builder'},{id:'a4',name:'MigrateAgent',purpose:'Migrations'},{id:'a5',name:'CacheAgent',purpose:'Caching'}], uses: ['ORM', 'Active Record', 'Data Mapper', 'Entities', 'Relations', 'Migrations', 'Multiple databases', 'TypeScript', 'Decorators', 'Caching'], frequency: 741, always_running: true },
];

// ═══════════════════════════════════════════════════════════════════════════════
// MESSAGE/QUEUE TOOLS (15 Tools)
// ═══════════════════════════════════════════════════════════════════════════════

export const MESSAGE_TOOLS = [
  { id: 'msg_1', name: 'Kafka', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'ProducerAgent',purpose:'Produce messages'},{id:'a2',name:'ConsumerAgent',purpose:'Consume messages'},{id:'a3',name:'PartitionAgent',purpose:'Partitioning'},{id:'a4',name:'StreamAgent',purpose:'Streams'},{id:'a5',name:'ConnectAgent',purpose:'Connect'}], uses: ['Event streaming', 'Log aggregation', 'Metrics', 'Messaging', 'Event sourcing', 'CQRS', 'Stream processing', 'CDC', 'Microservices', 'Real-time analytics'], frequency: 963, always_running: true },
  { id: 'msg_2', name: 'RabbitMQ', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'ExchangeAgent',purpose:'Exchanges'},{id:'a2',name:'QueueAgent',purpose:'Queues'},{id:'a3',name:'BindAgent',purpose:'Bindings'},{id:'a4',name:'PublishAgent',purpose:'Publishing'},{id:'a5',name:'ConsumeAgent',purpose:'Consuming'}], uses: ['Message broker', 'Work queues', 'Pub/Sub', 'Routing', 'RPC', 'Reliable delivery', 'Federation', 'Shovel', 'Clustering', 'Management'], frequency: 852, always_running: true },
  { id: 'msg_3', name: 'NATS', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'PubSubAgent',purpose:'Pub/Sub'},{id:'a2',name:'QueueAgent',purpose:'Queue groups'},{id:'a3',name:'JetStreamAgent',purpose:'JetStream'},{id:'a4',name:'ServiceAgent',purpose:'Services'},{id:'a5',name:'KeyValueAgent',purpose:'Key-Value'}], uses: ['Cloud messaging', 'Microservices', 'IoT', 'Edge computing', 'Real-time', 'Streaming', 'Key-Value', 'Object store', 'Request-reply', 'Load balancing'], frequency: 852, always_running: true },
  { id: 'msg_4', name: 'SQS', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'SendAgent',purpose:'Send messages'},{id:'a2',name:'ReceiveAgent',purpose:'Receive messages'},{id:'a3',name:'FIFOAgent',purpose:'FIFO queues'},{id:'a4',name:'DLQAgent',purpose:'Dead letter queues'},{id:'a5',name:'BatchAgent',purpose:'Batch operations'}], uses: ['Serverless queues', 'Decoupling', 'Fan-out', 'FIFO ordering', 'Dead letter queues', 'Lambda triggers', 'Auto-scaling', 'Pay per use', 'High throughput', 'Reliability'], frequency: 741, always_running: true },
  { id: 'msg_5', name: 'Redis Pub/Sub', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'PublishAgent',purpose:'Publish'},{id:'a2',name:'SubscribeAgent',purpose:'Subscribe'},{id:'a3',name:'ChannelAgent',purpose:'Channels'},{id:'a4',name:'PatternAgent',purpose:'Patterns'},{id:'a5',name:'StreamAgent',purpose:'Streams'}], uses: ['Real-time messaging', 'Notifications', 'Chat', 'Live updates', 'Broadcasting', 'Event notification', 'Presence', 'Simple pub/sub', 'Low latency', 'Streams'], frequency: 852, always_running: true },
  { id: 'msg_6', name: 'Pulsar', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'ProducerAgent',purpose:'Producing'},{id:'a2',name:'ConsumerAgent',purpose:'Consuming'},{id:'a3',name:'TenantAgent',purpose:'Multi-tenancy'},{id:'a4',name:'FunctionAgent',purpose:'Functions'},{id:'a5',name:'TieredAgent',purpose:'Tiered storage'}], uses: ['Unified messaging', 'Streaming', 'Multi-tenancy', 'Geo-replication', 'Functions', 'Tiered storage', 'Schema registry', 'Transactions', 'Queuing', 'Pub/Sub'], frequency: 741, always_running: true },
  { id: 'msg_7', name: 'ZeroMQ', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'SocketAgent',purpose:'Sockets'},{id:'a2',name:'PatternAgent',purpose:'Patterns'},{id:'a3',name:'TransportAgent',purpose:'Transports'},{id:'a4',name:'RouterAgent',purpose:'Routing'},{id:'a5',name:'ProxyAgent',purpose:'Proxying'}], uses: ['Message library', 'Patterns', 'Pub/Sub', 'Push/Pull', 'Request/Reply', 'Router/Dealer', 'High performance', 'Polyglot', 'Distributed', 'Embedded'], frequency: 639, always_running: true },
  { id: 'msg_8', name: 'BullMQ', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'QueueAgent',purpose:'Queues'},{id:'a2',name:'WorkerAgent',purpose:'Workers'},{id:'a3',name:'ScheduleAgent',purpose:'Scheduling'},{id:'a4',name:'FlowAgent',purpose:'Flows'},{id:'a5',name:'EventAgent',purpose:'Events'}], uses: ['Job queue', 'Background jobs', 'Scheduling', 'Rate limiting', 'Retries', 'Priorities', 'Flows', 'Events', 'Concurrency', 'Redis-based'], frequency: 741, always_running: true },
  { id: 'msg_9', name: 'Agenda', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'JobAgent',purpose:'Job management'},{id:'a2',name:'ScheduleAgent',purpose:'Scheduling'},{id:'a3',name:'ProcessAgent',purpose:'Processing'},{id:'a4',name:'ConcurrencyAgent',purpose:'Concurrency'},{id:'a5',name:'MonitorAgent',purpose:'Monitoring'}], uses: ['Job scheduling', 'Background jobs', 'Recurring jobs', 'MongoDB-backed', 'Priorities', 'Retries', 'Concurrency', 'Persistence', 'Node.js', 'Cron-like'], frequency: 639, always_running: true },
  { id: 'msg_10', name: 'Temporal', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'WorkflowAgent',purpose:'Workflows'},{id:'a2',name:'ActivityAgent',purpose:'Activities'},{id:'a3',name:'WorkerAgent',purpose:'Workers'},{id:'a4',name:'SignalAgent',purpose:'Signals'},{id:'a5',name:'QueryAgent',purpose:'Queries'}], uses: ['Workflow orchestration', 'Durable execution', 'Long-running', 'Retries', 'Compensation', 'Sagas', 'State management', 'Visibility', 'Versioning', 'Microservices'], frequency: 852, always_running: true },
  { id: 'msg_11', name: 'Inngest', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'FunctionAgent',purpose:'Functions'},{id:'a2',name:'EventAgent',purpose:'Events'},{id:'a3',name:'StepAgent',purpose:'Steps'},{id:'a4',name:'FlowAgent',purpose:'Flow control'},{id:'a5',name:'ObserveAgent',purpose:'Observability'}], uses: ['Event-driven functions', 'Background jobs', 'Scheduling', 'Retries', 'Steps', 'Branching', 'Debouncing', 'Rate limiting', 'Observability', 'TypeScript'], frequency: 741, always_running: true },
  { id: 'msg_12', name: 'Trigger.dev', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'JobAgent',purpose:'Jobs'},{id:'a2',name:'TriggerAgent',purpose:'Triggers'},{id:'a3',name:'IntegrationAgent',purpose:'Integrations'},{id:'a4',name:'LogAgent',purpose:'Logging'},{id:'a5',name:'DeployAgent',purpose:'Deployment'}], uses: ['Background jobs', 'Webhooks', 'Scheduled jobs', 'Integrations', 'Retries', 'Logging', 'TypeScript', 'API integrations', 'Long-running', 'Serverless'], frequency: 741, always_running: true },
  { id: 'msg_13', name: 'EventBridge', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'BusAgent',purpose:'Event bus'},{id:'a2',name:'RuleAgent',purpose:'Rules'},{id:'a3',name:'TargetAgent',purpose:'Targets'},{id:'a4',name:'ScheduleAgent',purpose:'Scheduling'},{id:'a5',name:'ArchiveAgent',purpose:'Archiving'}], uses: ['Event bus', 'Event routing', 'Event filtering', 'AWS integration', 'SaaS integration', 'Scheduling', 'Archive', 'Replay', 'Schema registry', 'Cross-account'], frequency: 741, always_running: true },
  { id: 'msg_14', name: 'SNS', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'TopicAgent',purpose:'Topics'},{id:'a2',name:'SubscribeAgent',purpose:'Subscriptions'},{id:'a3',name:'PublishAgent',purpose:'Publishing'},{id:'a4',name:'FilterAgent',purpose:'Filtering'},{id:'a5',name:'FIFOAgent',purpose:'FIFO'}], uses: ['Pub/Sub', 'Push notifications', 'SMS', 'Email', 'HTTP endpoints', 'Lambda', 'SQS', 'Fanout', 'Message filtering', 'FIFO'], frequency: 741, always_running: true },
  { id: 'msg_15', name: 'Cloudflare Queues', type: 'MESSAGE', intelligences: 5, agents: [{id:'a1',name:'QueueAgent',purpose:'Queue management'},{id:'a2',name:'ProducerAgent',purpose:'Producing'},{id:'a3',name:'ConsumerAgent',purpose:'Consuming'},{id:'a4',name:'BatchAgent',purpose:'Batching'},{id:'a5',name:'RetryAgent',purpose:'Retries'}], uses: ['Edge queues', 'Workers integration', 'Batching', 'Retries', 'Dead letter', 'Low latency', 'Global distribution', 'Serverless', 'Pay per use', 'Simple API'], frequency: 741, always_running: true },
];

// ═══════════════════════════════════════════════════════════════════════════════
// API/FRAMEWORK TOOLS (20 Tools)
// ═══════════════════════════════════════════════════════════════════════════════

export const API_TOOLS = [
  { id: 'api_1', name: 'GraphQL', type: 'API', intelligences: 5, agents: [{id:'a1',name:'SchemaAgent',purpose:'Schema'},{id:'a2',name:'ResolverAgent',purpose:'Resolvers'},{id:'a3',name:'QueryAgent',purpose:'Queries'},{id:'a4',name:'MutationAgent',purpose:'Mutations'},{id:'a5',name:'SubscriptionAgent',purpose:'Subscriptions'}], uses: ['API queries', 'Type system', 'Single endpoint', 'Introspection', 'Real-time', 'Federation', 'Caching', 'Batching', 'Mobile apps', 'BFF'], frequency: 963, always_running: true },
  { id: 'api_2', name: 'REST', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'Routing'},{id:'a2',name:'MethodAgent',purpose:'HTTP methods'},{id:'a3',name:'StatusAgent',purpose:'Status codes'},{id:'a4',name:'HeaderAgent',purpose:'Headers'},{id:'a5',name:'ResourceAgent',purpose:'Resources'}], uses: ['Web APIs', 'CRUD', 'Resource-based', 'Stateless', 'Caching', 'Versioning', 'Pagination', 'Filtering', 'Authentication', 'Documentation'], frequency: 963, always_running: true },
  { id: 'api_3', name: 'gRPC', type: 'API', intelligences: 5, agents: [{id:'a1',name:'ProtobufAgent',purpose:'Protobuf'},{id:'a2',name:'ServiceAgent',purpose:'Services'},{id:'a3',name:'StreamAgent',purpose:'Streaming'},{id:'a4',name:'InterceptAgent',purpose:'Interceptors'},{id:'a5',name:'LoadBalanceAgent',purpose:'Load balancing'}], uses: ['High performance', 'Streaming', 'Type safety', 'Code generation', 'Binary protocol', 'Bidirectional', 'Microservices', 'Mobile', 'Multi-language', 'Load balancing'], frequency: 852, always_running: true },
  { id: 'api_4', name: 'tRPC', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouterAgent',purpose:'Routers'},{id:'a2',name:'ProcedureAgent',purpose:'Procedures'},{id:'a3',name:'ContextAgent',purpose:'Context'},{id:'a4',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a5',name:'ClientAgent',purpose:'Client'}], uses: ['Type-safe APIs', 'End-to-end types', 'No code gen', 'React Query', 'Subscriptions', 'Batching', 'Full-stack TypeScript', 'Validation', 'Middleware', 'Testing'], frequency: 852, always_running: true },
  { id: 'api_5', name: 'OpenAPI', type: 'API', intelligences: 5, agents: [{id:'a1',name:'SpecAgent',purpose:'Specification'},{id:'a2',name:'ValidateAgent',purpose:'Validation'},{id:'a3',name:'GenerateAgent',purpose:'Code generation'},{id:'a4',name:'DocAgent',purpose:'Documentation'},{id:'a5',name:'MockAgent',purpose:'Mocking'}], uses: ['API specification', 'Documentation', 'Code generation', 'Validation', 'Testing', 'Mocking', 'SDK generation', 'Contract-first', 'Standards', 'Tooling'], frequency: 741, always_running: true },
  { id: 'api_6', name: 'Hono', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'Routing'},{id:'a2',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a3',name:'ContextAgent',purpose:'Context'},{id:'a4',name:'ValidatorAgent',purpose:'Validation'},{id:'a5',name:'AdapterAgent',purpose:'Adapters'}], uses: ['Edge framework', 'Multi-runtime', 'Fast', 'Middleware', 'Validation', 'OpenAPI', 'JSX', 'Testing', 'Cloudflare Workers', 'Bun'], frequency: 852, always_running: true },
  { id: 'api_7', name: 'Elysia', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'Routing'},{id:'a2',name:'TypeAgent',purpose:'Type inference'},{id:'a3',name:'PluginAgent',purpose:'Plugins'},{id:'a4',name:'SchemaAgent',purpose:'Schema'},{id:'a5',name:'SwaggerAgent',purpose:'Swagger'}], uses: ['Bun framework', 'Type safety', 'End-to-end types', 'Performance', 'Plugins', 'Validation', 'Swagger', 'WebSocket', 'Eden Treaty', 'Testing'], frequency: 852, always_running: true },
  { id: 'api_8', name: 'Fastify', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'Routing'},{id:'a2',name:'PluginAgent',purpose:'Plugins'},{id:'a3',name:'SchemaAgent',purpose:'Schema validation'},{id:'a4',name:'HookAgent',purpose:'Hooks'},{id:'a5',name:'DecoratorAgent',purpose:'Decorators'}], uses: ['Fast framework', 'Plugins', 'Schema validation', 'Hooks', 'TypeScript', 'Logging', 'Testing', 'OpenAPI', 'Decorators', 'Encapsulation'], frequency: 852, always_running: true },
  { id: 'api_9', name: 'Express', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'Routing'},{id:'a2',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a3',name:'RequestAgent',purpose:'Request handling'},{id:'a4',name:'ResponseAgent',purpose:'Response'},{id:'a5',name:'ErrorAgent',purpose:'Error handling'}], uses: ['Web framework', 'Middleware', 'Routing', 'Templates', 'Static files', 'Sessions', 'Authentication', 'RESTful', 'Ecosystem', 'Simplicity'], frequency: 852, always_running: true },
  { id: 'api_10', name: 'NestJS', type: 'API', intelligences: 5, agents: [{id:'a1',name:'ModuleAgent',purpose:'Modules'},{id:'a2',name:'ControllerAgent',purpose:'Controllers'},{id:'a3',name:'ServiceAgent',purpose:'Services'},{id:'a4',name:'GuardAgent',purpose:'Guards'},{id:'a5',name:'PipeAgent',purpose:'Pipes'}], uses: ['Enterprise framework', 'Modules', 'DI', 'TypeScript', 'GraphQL', 'Microservices', 'WebSockets', 'Testing', 'CLI', 'Documentation'], frequency: 963, always_running: true },
  // Continue with 10 more API tools...
  { id: 'api_11', name: 'Koa', type: 'API', intelligences: 5, agents: [{id:'a1',name:'ContextAgent',purpose:'Context'},{id:'a2',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a3',name:'RequestAgent',purpose:'Request'},{id:'a4',name:'ResponseAgent',purpose:'Response'},{id:'a5',name:'ErrorAgent',purpose:'Errors'}], uses: ['Lightweight framework', 'Async middleware', 'Context', 'Error handling', 'ES6+', 'Cascading', 'Testing', 'Routing', 'Body parsing', 'Sessions'], frequency: 741, always_running: true },
  { id: 'api_12', name: 'Adonis', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'Routing'},{id:'a2',name:'ControllerAgent',purpose:'Controllers'},{id:'a3',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a4',name:'ValidatorAgent',purpose:'Validation'},{id:'a5',name:'AuthAgent',purpose:'Authentication'}], uses: ['Full-stack framework', 'TypeScript', 'ORM', 'Authentication', 'Validation', 'CLI', 'Testing', 'Mailer', 'Sessions', 'Views'], frequency: 741, always_running: true },
  { id: 'api_13', name: 'Sails', type: 'API', intelligences: 5, agents: [{id:'a1',name:'BlueprintAgent',purpose:'Blueprints'},{id:'a2',name:'ModelAgent',purpose:'Models'},{id:'a3',name:'ControllerAgent',purpose:'Controllers'},{id:'a4',name:'PolicyAgent',purpose:'Policies'},{id:'a5',name:'HookAgent',purpose:'Hooks'}], uses: ['MVC framework', 'Blueprints', 'ORM', 'WebSockets', 'REST', 'Policies', 'Hooks', 'Data-driven', 'Enterprise', 'Real-time'], frequency: 639, always_running: true },
  { id: 'api_14', name: 'Feathers', type: 'API', intelligences: 5, agents: [{id:'a1',name:'ServiceAgent',purpose:'Services'},{id:'a2',name:'HookAgent',purpose:'Hooks'},{id:'a3',name:'TransportAgent',purpose:'Transports'},{id:'a4',name:'AuthAgent',purpose:'Authentication'},{id:'a5',name:'EventAgent',purpose:'Events'}], uses: ['Service-oriented', 'Real-time', 'REST', 'WebSockets', 'Authentication', 'Hooks', 'Database adapters', 'TypeScript', 'Microservices', 'Flexible'], frequency: 741, always_running: true },
  { id: 'api_15', name: 'Nitro', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'File routing'},{id:'a2',name:'HandlerAgent',purpose:'Handlers'},{id:'a3',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a4',name:'StorageAgent',purpose:'Storage'},{id:'a5',name:'CacheAgent',purpose:'Caching'}], uses: ['Universal server', 'File routing', 'Edge ready', 'Caching', 'Storage', 'Tasks', 'WebSockets', 'Auto imports', 'Nuxt engine', 'Multi-platform'], frequency: 852, always_running: true },
  { id: 'api_16', name: 'H3', type: 'API', intelligences: 5, agents: [{id:'a1',name:'EventAgent',purpose:'Events'},{id:'a2',name:'RouteAgent',purpose:'Routing'},{id:'a3',name:'UtilAgent',purpose:'Utilities'},{id:'a4',name:'BodyAgent',purpose:'Body parsing'},{id:'a5',name:'CookieAgent',purpose:'Cookies'}], uses: ['Minimal HTTP', 'Edge ready', 'High performance', 'Composable', 'TypeScript', 'Body parsing', 'Cookies', 'Query', 'Headers', 'Proxy'], frequency: 741, always_running: true },
  { id: 'api_17', name: 'ElysiaJS', type: 'API', intelligences: 5, agents: [{id:'a1',name:'TypeAgent',purpose:'Type system'},{id:'a2',name:'PluginAgent',purpose:'Plugins'},{id:'a3',name:'LifecycleAgent',purpose:'Lifecycle'},{id:'a4',name:'ValidationAgent',purpose:'Validation'},{id:'a5',name:'SwaggerAgent',purpose:'OpenAPI'}], uses: ['Type-safe', 'Performance', 'Bun native', 'Plugins', 'Validation', 'OpenAPI', 'WebSocket', 'GraphQL', 'End-to-end types', 'Testing'], frequency: 852, always_running: true },
  { id: 'api_18', name: 'Oak', type: 'API', intelligences: 5, agents: [{id:'a1',name:'AppAgent',purpose:'Application'},{id:'a2',name:'RouterAgent',purpose:'Router'},{id:'a3',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a4',name:'ContextAgent',purpose:'Context'},{id:'a5',name:'HelperAgent',purpose:'Helpers'}], uses: ['Deno framework', 'Middleware', 'Routing', 'Context', 'TypeScript native', 'HTTP/2', 'WebSocket', 'Testing', 'Static files', 'Templates'], frequency: 639, always_running: true },
  { id: 'api_19', name: 'Fresh', type: 'API', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'File routing'},{id:'a2',name:'IslandAgent',purpose:'Islands'},{id:'a3',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a4',name:'HandlerAgent',purpose:'Handlers'},{id:'a5',name:'PluginAgent',purpose:'Plugins'}], uses: ['Deno framework', 'Islands architecture', 'Zero JS', 'JIT rendering', 'Edge native', 'TypeScript', 'No build step', 'Preact', 'File routing', 'Middleware'], frequency: 741, always_running: true },
  { id: 'api_20', name: 'Bun HTTP', type: 'API', intelligences: 5, agents: [{id:'a1',name:'ServerAgent',purpose:'Server'},{id:'a2',name:'FetchAgent',purpose:'Fetch handler'},{id:'a3',name:'WebSocketAgent',purpose:'WebSocket'},{id:'a4',name:'FileAgent',purpose:'File serving'},{id:'a5',name:'TLSAgent',purpose:'TLS'}], uses: ['Native Bun server', 'High performance', 'Fetch API', 'WebSocket', 'File serving', 'TLS', 'Streaming', 'Low memory', 'Hot reload', 'Simple API'], frequency: 852, always_running: true },
];

// ═══════════════════════════════════════════════════════════════════════════════
// INFRASTRUCTURE TOOLS (20 Tools)
// ═══════════════════════════════════════════════════════════════════════════════

export const INFRASTRUCTURE_TOOLS = [
  { id: 'inf_1', name: 'Docker', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ContainerAgent',purpose:'Containers'},{id:'a2',name:'ImageAgent',purpose:'Images'},{id:'a3',name:'NetworkAgent',purpose:'Networking'},{id:'a4',name:'VolumeAgent',purpose:'Volumes'},{id:'a5',name:'ComposeAgent',purpose:'Compose'}], uses: ['Containerization', 'Dev environments', 'CI/CD', 'Microservices', 'Isolation', 'Portability', 'Scaling', 'Networking', 'Volumes', 'Multi-stage builds'], frequency: 963, always_running: true },
  { id: 'inf_2', name: 'Kubernetes', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'PodAgent',purpose:'Pods'},{id:'a2',name:'ServiceAgent',purpose:'Services'},{id:'a3',name:'DeployAgent',purpose:'Deployments'},{id:'a4',name:'ConfigAgent',purpose:'ConfigMaps'},{id:'a5',name:'SecretAgent',purpose:'Secrets'}], uses: ['Container orchestration', 'Scaling', 'Load balancing', 'Self-healing', 'Rolling updates', 'Service discovery', 'Storage', 'Networking', 'RBAC', 'Extensions'], frequency: 963, always_running: true },
  { id: 'inf_3', name: 'Terraform', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ProviderAgent',purpose:'Providers'},{id:'a2',name:'ResourceAgent',purpose:'Resources'},{id:'a3',name:'StateAgent',purpose:'State'},{id:'a4',name:'PlanAgent',purpose:'Planning'},{id:'a5',name:'ModuleAgent',purpose:'Modules'}], uses: ['IaC', 'Multi-cloud', 'State management', 'Modules', 'Providers', 'Planning', 'Workspaces', 'Import', 'Drift detection', 'Automation'], frequency: 852, always_running: true },
  { id: 'inf_4', name: 'Pulumi', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'StackAgent',purpose:'Stacks'},{id:'a2',name:'ResourceAgent',purpose:'Resources'},{id:'a3',name:'OutputAgent',purpose:'Outputs'},{id:'a4',name:'ConfigAgent',purpose:'Config'},{id:'a5',name:'SecretAgent',purpose:'Secrets'}], uses: ['IaC with code', 'Multi-cloud', 'TypeScript/Python/Go', 'State', 'Secrets', 'Testing', 'CI/CD', 'Automation', 'Components', 'Policies'], frequency: 852, always_running: true },
  { id: 'inf_5', name: 'Helm', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ChartAgent',purpose:'Charts'},{id:'a2',name:'ReleaseAgent',purpose:'Releases'},{id:'a3',name:'RepoAgent',purpose:'Repositories'},{id:'a4',name:'TemplateAgent',purpose:'Templates'},{id:'a5',name:'ValueAgent',purpose:'Values'}], uses: ['K8s package manager', 'Charts', 'Templating', 'Releases', 'Rollback', 'Repositories', 'Dependencies', 'Hooks', 'Testing', 'GitOps'], frequency: 741, always_running: true },
  { id: 'inf_6', name: 'ArgoCD', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'AppAgent',purpose:'Applications'},{id:'a2',name:'SyncAgent',purpose:'Sync'},{id:'a3',name:'RollbackAgent',purpose:'Rollback'},{id:'a4',name:'ProjectAgent',purpose:'Projects'},{id:'a5',name:'RepoAgent',purpose:'Repositories'}], uses: ['GitOps', 'K8s deployment', 'Sync', 'Rollback', 'Multi-cluster', 'SSO', 'RBAC', 'Webhooks', 'Health checks', 'Notifications'], frequency: 852, always_running: true },
  { id: 'inf_7', name: 'Prometheus', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ScrapeAgent',purpose:'Scraping'},{id:'a2',name:'QueryAgent',purpose:'PromQL'},{id:'a3',name:'AlertAgent',purpose:'Alerting'},{id:'a4',name:'StorageAgent',purpose:'Storage'},{id:'a5',name:'FederateAgent',purpose:'Federation'}], uses: ['Monitoring', 'Metrics', 'PromQL', 'Alerting', 'Service discovery', 'Federation', 'Recording rules', 'Exporters', 'Time series', 'Kubernetes'], frequency: 963, always_running: true },
  { id: 'inf_8', name: 'Grafana', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'DashboardAgent',purpose:'Dashboards'},{id:'a2',name:'PanelAgent',purpose:'Panels'},{id:'a3',name:'DataSourceAgent',purpose:'Data sources'},{id:'a4',name:'AlertAgent',purpose:'Alerting'},{id:'a5',name:'UserAgent',purpose:'Users/teams'}], uses: ['Visualization', 'Dashboards', 'Alerting', 'Data sources', 'Plugins', 'Annotations', 'Variables', 'Sharing', 'Teams', 'Enterprise'], frequency: 852, always_running: true },
  { id: 'inf_9', name: 'Jaeger', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'TraceAgent',purpose:'Tracing'},{id:'a2',name:'SpanAgent',purpose:'Spans'},{id:'a3',name:'ServiceAgent',purpose:'Service graphs'},{id:'a4',name:'QueryAgent',purpose:'Querying'},{id:'a5',name:'StorageAgent',purpose:'Storage'}], uses: ['Distributed tracing', 'Service graphs', 'Root cause', 'Performance', 'Dependencies', 'OpenTelemetry', 'Sampling', 'Analytics', 'Comparison', 'Debugging'], frequency: 741, always_running: true },
  { id: 'inf_10', name: 'OpenTelemetry', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'TraceAgent',purpose:'Traces'},{id:'a2',name:'MetricAgent',purpose:'Metrics'},{id:'a3',name:'LogAgent',purpose:'Logs'},{id:'a4',name:'CollectorAgent',purpose:'Collector'},{id:'a5',name:'SDKAgent',purpose:'SDK'}], uses: ['Observability', 'Traces', 'Metrics', 'Logs', 'Vendor neutral', 'Auto-instrumentation', 'Context propagation', 'Sampling', 'Export', 'Standards'], frequency: 852, always_running: true },
  // Continue with 10 more infrastructure tools...
  { id: 'inf_11', name: 'Datadog', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'MetricAgent',purpose:'Metrics'},{id:'a2',name:'APMAgent',purpose:'APM'},{id:'a3',name:'LogAgent',purpose:'Logs'},{id:'a4',name:'MonitorAgent',purpose:'Monitors'},{id:'a5',name:'DashboardAgent',purpose:'Dashboards'}], uses: ['Full observability', 'Metrics', 'APM', 'Logs', 'RUM', 'Synthetics', 'Security', 'CI', 'Database monitoring', 'Network monitoring'], frequency: 852, always_running: true },
  { id: 'inf_12', name: 'Sentry', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ErrorAgent',purpose:'Error tracking'},{id:'a2',name:'PerformanceAgent',purpose:'Performance'},{id:'a3',name:'ReleaseAgent',purpose:'Releases'},{id:'a4',name:'AlertAgent',purpose:'Alerts'},{id:'a5',name:'SessionAgent',purpose:'Session replay'}], uses: ['Error tracking', 'Performance monitoring', 'Releases', 'Session replay', 'Profiling', 'Crons', 'Alerts', 'Integrations', 'Source maps', 'Issues'], frequency: 852, always_running: true },
  { id: 'inf_13', name: 'PagerDuty', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'IncidentAgent',purpose:'Incidents'},{id:'a2',name:'OnCallAgent',purpose:'On-call'},{id:'a3',name:'EscalateAgent',purpose:'Escalation'},{id:'a4',name:'ServiceAgent',purpose:'Services'},{id:'a5',name:'AutomateAgent',purpose:'Automation'}], uses: ['Incident management', 'On-call', 'Escalation', 'Automation', 'Integrations', 'Analytics', 'Postmortems', 'Status pages', 'Runbooks', 'AIOps'], frequency: 741, always_running: true },
  { id: 'inf_14', name: 'Vault', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'SecretAgent',purpose:'Secrets'},{id:'a2',name:'AuthAgent',purpose:'Auth methods'},{id:'a3',name:'EncryptAgent',purpose:'Encryption'},{id:'a4',name:'PolicyAgent',purpose:'Policies'},{id:'a5',name:'AuditAgent',purpose:'Audit'}], uses: ['Secrets management', 'Encryption as a service', 'Dynamic secrets', 'PKI', 'SSH', 'Database credentials', 'Cloud credentials', 'Transit encryption', 'Policies', 'Audit'], frequency: 963, always_running: true },
  { id: 'inf_15', name: 'Consul', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ServiceAgent',purpose:'Service discovery'},{id:'a2',name:'KVAgent',purpose:'KV store'},{id:'a3',name:'HealthAgent',purpose:'Health checks'},{id:'a4',name:'ConnectAgent',purpose:'Service mesh'},{id:'a5',name:'ConfigAgent',purpose:'Config'}], uses: ['Service discovery', 'Service mesh', 'KV store', 'Health checks', 'Multi-datacenter', 'DNS', 'ACL', 'Intentions', 'Config entries', 'Catalog'], frequency: 741, always_running: true },
  { id: 'inf_16', name: 'Istio', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'TrafficAgent',purpose:'Traffic management'},{id:'a2',name:'SecurityAgent',purpose:'Security'},{id:'a3',name:'ObserveAgent',purpose:'Observability'},{id:'a4',name:'PolicyAgent',purpose:'Policies'},{id:'a5',name:'GatewayAgent',purpose:'Gateway'}], uses: ['Service mesh', 'Traffic management', 'Security', 'Observability', 'mTLS', 'Rate limiting', 'Canary', 'Circuit breaking', 'Fault injection', 'Multi-cluster'], frequency: 852, always_running: true },
  { id: 'inf_17', name: 'Linkerd', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ProxyAgent',purpose:'Proxy'},{id:'a2',name:'mTLSAgent',purpose:'mTLS'},{id:'a3',name:'LoadAgent',purpose:'Load balancing'},{id:'a4',name:'RetryAgent',purpose:'Retries'},{id:'a5',name:'MetricAgent',purpose:'Metrics'}], uses: ['Service mesh', 'mTLS', 'Load balancing', 'Retries', 'Timeouts', 'Metrics', 'Low overhead', 'Simple', 'Multi-cluster', 'Traffic split'], frequency: 741, always_running: true },
  { id: 'inf_18', name: 'Envoy', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ListenerAgent',purpose:'Listeners'},{id:'a2',name:'ClusterAgent',purpose:'Clusters'},{id:'a3',name:'RouteAgent',purpose:'Routes'},{id:'a4',name:'FilterAgent',purpose:'Filters'},{id:'a5',name:'HealthAgent',purpose:'Health checking'}], uses: ['L7 proxy', 'Service mesh data plane', 'Load balancing', 'gRPC', 'HTTP/2', 'Rate limiting', 'Circuit breaking', 'Tracing', 'Statistics', 'Access logging'], frequency: 852, always_running: true },
  { id: 'inf_19', name: 'Traefik', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'RouteAgent',purpose:'Routing'},{id:'a2',name:'LoadAgent',purpose:'Load balancing'},{id:'a3',name:'MiddlewareAgent',purpose:'Middleware'},{id:'a4',name:'TLSAgent',purpose:'TLS'},{id:'a5',name:'ProviderAgent',purpose:'Providers'}], uses: ['Reverse proxy', 'Load balancer', 'Auto-discovery', 'Let\'s Encrypt', 'Middleware', 'K8s ingress', 'Docker', 'Rate limiting', 'Circuit breaker', 'Metrics'], frequency: 741, always_running: true },
  { id: 'inf_20', name: 'NGINX', type: 'INFRASTRUCTURE', intelligences: 5, agents: [{id:'a1',name:'ServerAgent',purpose:'Server blocks'},{id:'a2',name:'LocationAgent',purpose:'Locations'},{id:'a3',name:'UpstreamAgent',purpose:'Upstreams'},{id:'a4',name:'CacheAgent',purpose:'Caching'},{id:'a5',name:'SSLAgent',purpose:'SSL'}], uses: ['Web server', 'Reverse proxy', 'Load balancer', 'Caching', 'SSL termination', 'Rate limiting', 'Static files', 'API gateway', 'WebSocket', 'High performance'], frequency: 963, always_running: true },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SECURITY TOOLS (15 Tools)
// ═══════════════════════════════════════════════════════════════════════════════

export const SECURITY_TOOLS = [
  { id: 'sec_1', name: 'OAuth2', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'AuthzAgent',purpose:'Authorization'},{id:'a2',name:'TokenAgent',purpose:'Tokens'},{id:'a3',name:'ScopeAgent',purpose:'Scopes'},{id:'a4',name:'RefreshAgent',purpose:'Refresh tokens'},{id:'a5',name:'GrantAgent',purpose:'Grant types'}], uses: ['Authorization', 'Access tokens', 'Refresh tokens', 'Scopes', 'Grant types', 'PKCE', 'Delegated access', 'Third-party apps', 'API protection', 'Standards'], frequency: 963, always_running: true },
  { id: 'sec_2', name: 'JWT', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'SignAgent',purpose:'Signing'},{id:'a2',name:'VerifyAgent',purpose:'Verification'},{id:'a3',name:'ClaimAgent',purpose:'Claims'},{id:'a4',name:'ExpireAgent',purpose:'Expiration'},{id:'a5',name:'RefreshAgent',purpose:'Refresh'}], uses: ['Stateless auth', 'Claims', 'Signing', 'Verification', 'Access tokens', 'ID tokens', 'Expiration', 'Refresh', 'Compact', 'Self-contained'], frequency: 963, always_running: true },
  { id: 'sec_3', name: 'Passport', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'StrategyAgent',purpose:'Strategies'},{id:'a2',name:'SessionAgent',purpose:'Sessions'},{id:'a3',name:'SerializeAgent',purpose:'Serialization'},{id:'a4',name:'LocalAgent',purpose:'Local auth'},{id:'a5',name:'SocialAgent',purpose:'Social auth'}], uses: ['Authentication middleware', 'Strategies', 'Local auth', 'OAuth', 'OpenID', 'SAML', 'Sessions', 'Multiple providers', 'Custom strategies', 'Node.js'], frequency: 852, always_running: true },
  { id: 'sec_4', name: 'NextAuth', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'ProviderAgent',purpose:'Providers'},{id:'a2',name:'SessionAgent',purpose:'Sessions'},{id:'a3',name:'CallbackAgent',purpose:'Callbacks'},{id:'a4',name:'AdapterAgent',purpose:'Adapters'},{id:'a5',name:'JWTAgent',purpose:'JWT'}], uses: ['Next.js auth', 'Multiple providers', 'Sessions', 'JWT', 'Database adapters', 'OAuth', 'Email', 'Credentials', 'Custom providers', 'TypeScript'], frequency: 852, always_running: true },
  { id: 'sec_5', name: 'Clerk', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'UserAgent',purpose:'User management'},{id:'a2',name:'AuthAgent',purpose:'Authentication'},{id:'a3',name:'SessionAgent',purpose:'Sessions'},{id:'a4',name:'OrgAgent',purpose:'Organizations'},{id:'a5',name:'ComponentAgent',purpose:'Components'}], uses: ['Complete auth', 'User management', 'Organizations', 'Multi-factor', 'Social login', 'Magic links', 'SSO', 'Session management', 'Embeddables', 'API'], frequency: 852, always_running: true },
  { id: 'sec_6', name: 'Auth0', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'AuthAgent',purpose:'Authentication'},{id:'a2',name:'UserAgent',purpose:'User management'},{id:'a3',name:'RuleAgent',purpose:'Rules'},{id:'a4',name:'ActionAgent',purpose:'Actions'},{id:'a5',name:'LogAgent',purpose:'Logs'}], uses: ['Identity platform', 'Universal login', 'Social connections', 'Enterprise SSO', 'MFA', 'Rules', 'Actions', 'User management', 'APIs', 'Machine-to-machine'], frequency: 852, always_running: true },
  { id: 'sec_7', name: 'Keycloak', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'RealmAgent',purpose:'Realms'},{id:'a2',name:'UserAgent',purpose:'Users'},{id:'a3',name:'ClientAgent',purpose:'Clients'},{id:'a4',name:'RoleAgent',purpose:'Roles'},{id:'a5',name:'FederateAgent',purpose:'Federation'}], uses: ['IAM', 'SSO', 'OpenID Connect', 'OAuth 2.0', 'SAML', 'LDAP', 'Social login', 'User federation', 'Admin console', 'Self-hosted'], frequency: 741, always_running: true },
  { id: 'sec_8', name: 'bcrypt', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'HashAgent',purpose:'Hashing'},{id:'a2',name:'SaltAgent',purpose:'Salting'},{id:'a3',name:'VerifyAgent',purpose:'Verification'},{id:'a4',name:'CostAgent',purpose:'Work factor'},{id:'a5',name:'CompareAgent',purpose:'Comparison'}], uses: ['Password hashing', 'Salting', 'Work factor', 'Secure comparison', 'Verification', 'Protection', 'Industry standard', 'Resistant to attacks', 'Node.js', 'Cross-platform'], frequency: 741, always_running: true },
  { id: 'sec_9', name: 'Argon2', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'HashAgent',purpose:'Hashing'},{id:'a2',name:'MemoryAgent',purpose:'Memory cost'},{id:'a3',name:'TimeAgent',purpose:'Time cost'},{id:'a4',name:'ParallelAgent',purpose:'Parallelism'},{id:'a5',name:'VerifyAgent',purpose:'Verification'}], uses: ['Password hashing', 'Memory-hard', 'Time cost', 'Parallelism', 'PHC winner', 'Modern standard', 'GPU resistant', 'Side-channel resistant', 'Configurable', 'Secure'], frequency: 852, always_running: true },
  { id: 'sec_10', name: 'CORS', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'OriginAgent',purpose:'Origin checking'},{id:'a2',name:'MethodAgent',purpose:'Methods'},{id:'a3',name:'HeaderAgent',purpose:'Headers'},{id:'a4',name:'CredentialAgent',purpose:'Credentials'},{id:'a5',name:'PreflightAgent',purpose:'Preflight'}], uses: ['Cross-origin', 'Origin validation', 'Allowed methods', 'Allowed headers', 'Credentials', 'Preflight', 'Max age', 'Exposed headers', 'Browser security', 'API protection'], frequency: 852, always_running: true },
  { id: 'sec_11', name: 'Helmet', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'CSPAgent',purpose:'CSP'},{id:'a2',name:'HSTSAgent',purpose:'HSTS'},{id:'a3',name:'XFrameAgent',purpose:'X-Frame-Options'},{id:'a4',name:'XSSAgent',purpose:'XSS protection'},{id:'a5',name:'NoSniffAgent',purpose:'No sniff'}], uses: ['Security headers', 'CSP', 'HSTS', 'X-Frame-Options', 'XSS protection', 'No sniff', 'DNS prefetch', 'Referrer policy', 'Express middleware', 'Best practices'], frequency: 852, always_running: true },
  { id: 'sec_12', name: 'CSRF', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'TokenAgent',purpose:'CSRF tokens'},{id:'a2',name:'ValidateAgent',purpose:'Validation'},{id:'a3',name:'CookieAgent',purpose:'Cookies'},{id:'a4',name:'OriginAgent',purpose:'Origin check'},{id:'a5',name:'RefererAgent',purpose:'Referer check'}], uses: ['CSRF protection', 'Token generation', 'Token validation', 'Cookie settings', 'Origin checking', 'Referer checking', 'Double submit', 'Synchronizer token', 'SameSite cookies', 'Form protection'], frequency: 741, always_running: true },
  { id: 'sec_13', name: 'Rate Limiting', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'WindowAgent',purpose:'Time windows'},{id:'a2',name:'CountAgent',purpose:'Request counting'},{id:'a3',name:'ThrottleAgent',purpose:'Throttling'},{id:'a4',name:'KeyAgent',purpose:'Key generation'},{id:'a5',name:'StoreAgent',purpose:'Storage'}], uses: ['API protection', 'DDoS prevention', 'Abuse prevention', 'Fair usage', 'Sliding window', 'Fixed window', 'Token bucket', 'Leaky bucket', 'Distributed', 'Customizable'], frequency: 852, always_running: true },
  { id: 'sec_14', name: 'WAF', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'RuleAgent',purpose:'Rules'},{id:'a2',name:'FilterAgent',purpose:'Filtering'},{id:'a3',name:'BlockAgent',purpose:'Blocking'},{id:'a4',name:'LogAgent',purpose:'Logging'},{id:'a5',name:'BotAgent',purpose:'Bot detection'}], uses: ['Web application firewall', 'Rule engine', 'SQL injection', 'XSS prevention', 'Bot management', 'Rate limiting', 'IP blocking', 'Geo blocking', 'Custom rules', 'Logging'], frequency: 963, always_running: true },
  { id: 'sec_15', name: 'OWASP ZAP', type: 'SECURITY', intelligences: 5, agents: [{id:'a1',name:'ScanAgent',purpose:'Scanning'},{id:'a2',name:'SpiderAgent',purpose:'Spidering'},{id:'a3',name:'FuzzAgent',purpose:'Fuzzing'},{id:'a4',name:'ReportAgent',purpose:'Reporting'},{id:'a5',name:'AutomateAgent',purpose:'Automation'}], uses: ['Security testing', 'Vulnerability scanning', 'Spider', 'Fuzzing', 'Active scan', 'Passive scan', 'API scan', 'Authentication', 'Reporting', 'CI/CD integration'], frequency: 741, always_running: true },
];

// ═══════════════════════════════════════════════════════════════════════════════
// TOTALS
// ═══════════════════════════════════════════════════════════════════════════════

export const BACKEND_TOOL_TOTALS = {
  DATABASE_TOOLS: DATABASE_TOOLS.length,
  MESSAGE_TOOLS: MESSAGE_TOOLS.length,
  API_TOOLS: API_TOOLS.length,
  INFRASTRUCTURE_TOOLS: INFRASTRUCTURE_TOOLS.length,
  SECURITY_TOOLS: SECURITY_TOOLS.length,
  TOTAL_TOOLS: DATABASE_TOOLS.length + MESSAGE_TOOLS.length + API_TOOLS.length + INFRASTRUCTURE_TOOLS.length + SECURITY_TOOLS.length,
  AGENTS_PER_TOOL: 5,
  TOTAL_AGENTS: (DATABASE_TOOLS.length + MESSAGE_TOOLS.length + API_TOOLS.length + INFRASTRUCTURE_TOOLS.length + SECURITY_TOOLS.length) * 5,
  USES_PER_TOOL: 10,
  TOTAL_USES: (DATABASE_TOOLS.length + MESSAGE_TOOLS.length + API_TOOLS.length + INFRASTRUCTURE_TOOLS.length + SECURITY_TOOLS.length) * 10,
  ALL_NOW: true,
  NOT_FUTURE: true,
};

export default {
  DATABASE_TOOLS,
  MESSAGE_TOOLS,
  API_TOOLS,
  INFRASTRUCTURE_TOOLS,
  SECURITY_TOOLS,
  BACKEND_TOOL_TOTALS,
};
