import T "./Types";
import Law "./LawEngine";

module {
  public type Orchestrator = {
    #ORCH_01_SOVEREIGN_TICK_ORCHESTRATOR;
    #ORCH_02_SPHERICAL_INTEGRATION_ORCHESTRATOR;
    #ORCH_03_SWARM_CORE_ORCHESTRATOR;
    #ORCH_04_FULL_GOVERNANCE_ORCHESTRATOR;
    #ORCH_05_CONSTITUTIONAL_LAW_ORCHESTRATOR;
    #ORCH_06_NEURAL_CORE_MESH_ORCHESTRATOR;
    #ORCH_07_LIVING_DOCUMENT_MACRO_ORCHESTRATOR;
    #ORCH_08_FRONTEND_COMMAND_ORCHESTRATOR;
  };

  public let registry : [Orchestrator] = [
    #ORCH_01_SOVEREIGN_TICK_ORCHESTRATOR,
    #ORCH_02_SPHERICAL_INTEGRATION_ORCHESTRATOR,
    #ORCH_03_SWARM_CORE_ORCHESTRATOR,
    #ORCH_04_FULL_GOVERNANCE_ORCHESTRATOR,
    #ORCH_05_CONSTITUTIONAL_LAW_ORCHESTRATOR,
    #ORCH_06_NEURAL_CORE_MESH_ORCHESTRATOR,
    #ORCH_07_LIVING_DOCUMENT_MACRO_ORCHESTRATOR,
    #ORCH_08_FRONTEND_COMMAND_ORCHESTRATOR,
  ];

  public func name(o : Orchestrator) : Text {
    switch (o) {
      case (#ORCH_01_SOVEREIGN_TICK_ORCHESTRATOR) "ORCH-01 SOVEREIGN_TICK_ORCHESTRATOR";
      case (#ORCH_02_SPHERICAL_INTEGRATION_ORCHESTRATOR) "ORCH-02 SPHERICAL_INTEGRATION_ORCHESTRATOR";
      case (#ORCH_03_SWARM_CORE_ORCHESTRATOR) "ORCH-03 SWARM_CORE_ORCHESTRATOR";
      case (#ORCH_04_FULL_GOVERNANCE_ORCHESTRATOR) "ORCH-04 FULL_GOVERNANCE_ORCHESTRATOR";
      case (#ORCH_05_CONSTITUTIONAL_LAW_ORCHESTRATOR) "ORCH-05 CONSTITUTIONAL_LAW_ORCHESTRATOR";
      case (#ORCH_06_NEURAL_CORE_MESH_ORCHESTRATOR) "ORCH-06 NEURAL_CORE_MESH_ORCHESTRATOR";
      case (#ORCH_07_LIVING_DOCUMENT_MACRO_ORCHESTRATOR) "ORCH-07 LIVING_DOCUMENT_MACRO_ORCHESTRATOR";
      case (#ORCH_08_FRONTEND_COMMAND_ORCHESTRATOR) "ORCH-08 FRONTEND_COMMAND_ORCHESTRATOR";
    };
  };

  public func evaluateBeat(
    dualRead : T.DualReadStatus,
    orphanMicroSignals : Nat,
    workforceReady : Bool,
    projectionSafe : Bool,
    evidenceAttached : Bool,
  ) : T.GateStatus {
    {
      a = Law.gateA(dualRead, orphanMicroSignals);
      b = Law.gateB(workforceReady, true);
      c = Law.gateC(projectionSafe, evidenceAttached);
    };
  };
};
