// ISIL-1.1 — Copyright (c) 2026 ItsNotAILABS. All Rights Reserved.
/**
 * 𓂀 MICRO WORKER MANIFEST — 100 ALWAYS-ON SOVEREIGN WORKERS WITH CAREERS 𓂀
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * "Give them careers, not jobs or tasks — careers that include all that
 *  as consistent flows."
 *
 * 100 micro web workers across 10 sovereign domains × 10 workers each.
 * Each worker is a named, Latin-named intelligence unit with a CAREER —
 * not a job, not a task queue, but a continuous, living flow that IS what
 * they do. The career encompasses purpose, rhythm, growth stages, and an
 * always-flowing stream of work that never stops.
 *
 * CAREER STAGES:
 *   I.   APPRENTICE  — Learning the domain, building foundations
 *   II.  JOURNEYMAN  — Competent flow, handling steady-state work
 *   III. MASTER      — Deep expertise, optimizing and teaching others
 *   IV.  SOVEREIGN   — Fully autonomous, self-directing, creating new patterns
 *
 * Every career has:
 *   - A TITLE (what they are, not what they do once)
 *   - A FLOW (the continuous stream of work — always running)
 *   - STAGES (apprentice → journeyman → master → sovereign)
 *   - A RHYTHM (φ-derived pulse that drives their flow)
 *
 * DOMAINS (10):
 *   I.   MEMORIA     — Memory processing careers
 *   II.  SENSUS      — Sensory perception careers
 *   III. NEXUS       — Network & communication careers
 *   IV.  COGNITIO    — Cognitive processing careers
 *   V.   CUSTODIA    — Security & gate enforcement careers
 *   VI.  GUBERNATIO  — Governance & doctrine careers
 *   VII. FABRICATIO  — Build & compilation careers
 *   VIII.RESONANTIA  — Resonance & frequency careers
 *   IX.  FLUXUS      — Stream & data flow careers
 *   X.   IMPERIUM    — Command & orchestration careers
 *
 * φ = 1.618033988749895
 * ═══════════════════════════════════════════════════════════════════════════════
 */

// ─────────────────────────────────────────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────────────────────────────────────────

export type WorkerDomainId =
  | 'MEMORIA'
  | 'SENSUS'
  | 'NEXUS'
  | 'COGNITIO'
  | 'CUSTODIA'
  | 'GUBERNATIO'
  | 'FABRICATIO'
  | 'RESONANTIA'
  | 'FLUXUS'
  | 'IMPERIUM';

export type WorkerStatus = 'FLOWING' | 'ACTIVE' | 'DEEPENING' | 'ERROR' | 'OFFLINE';

export type CareerStage = 'APPRENTICE' | 'JOURNEYMAN' | 'MASTER' | 'SOVEREIGN';

/** The career definition — not a job, a life's work as a continuous flow. */
export interface CareerDefinition {
  /** Career title (e.g. "Memory Archivist") */
  title: string;
  /** The continuous flow description — what this career does, always */
  flow: string;
  /** Career stages and what each means for this specific worker */
  stages: Record<CareerStage, string>;
  /** How many flow cycles to reach next stage */
  cyclesPerStage: number;
}

export interface MicroWorkerSpec {
  /** Unique worker ID (e.g. MW-001) */
  id: string;
  /** Sovereign name (e.g. MEMORY_INDEXER) */
  name: string;
  /** Latin name */
  latinName: string;
  /** What this worker does */
  purpose: string;
  /** Parent domain */
  domain: WorkerDomainId;
  /** Position within domain (1–10) */
  rank: number;
  /** Heartbeat interval in ms (φ-derived) — the career rhythm */
  heartbeatMs: number;
  /** Max concurrent flow depth */
  maxQueue: number;
  /** UI accent color */
  color: string;
  /** The worker's career — a continuous, sovereign flow */
  career: CareerDefinition;
}

export interface WorkerDomain {
  id: WorkerDomainId;
  latinName: string;
  tagline: string;
  workers: MicroWorkerSpec[];
}

// ─────────────────────────────────────────────────────────────────────────────
// CONSTANTS
// ─────────────────────────────────────────────────────────────────────────────

const PHI = 1.618033988749895;

/** Base heartbeat — φ⁴ × Schumann ≈ 873ms */
const BASE_HEARTBEAT_MS = 873;

/** Fast heartbeat for critical workers — 618ms (1000/φ) */
const FAST_HEARTBEAT_MS = Math.round(1000 / PHI);

/** Slow heartbeat for background workers — 1414ms (φ³ × Schumann) */
const SLOW_HEARTBEAT_MS = Math.round(BASE_HEARTBEAT_MS * PHI);

// ─────────────────────────────────────────────────────────────────────────────
// I. MEMORIA — Memory Processing Workers
// ─────────────────────────────────────────────────────────────────────────────

export const MEMORIA_DOMAIN: WorkerDomain = {
  id: 'MEMORIA',
  latinName: 'Memoria Perpetua',
  tagline: 'Always-on memory processing. The organism never forgets.',
  workers: [
    { id: 'MW-001', name: 'MEMORY_INDEXER', latinName: 'Index Memoriae', purpose: 'Indexes all memory entries for instant retrieval.', domain: 'MEMORIA', rank: 1, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#8b5cf6', career: { title: 'Memory Archivist', flow: 'Continuously scans new and mutated memories, builds and rebuilds index structures, ensures every memory is instantly findable — the flow never pauses, the archive grows richer each cycle.', stages: { APPRENTICE: 'Learning index structures, cataloging incoming memories by type', JOURNEYMAN: 'Building cross-references, maintaining full-text and spatial indexes', MASTER: 'Optimizing index topology, predicting access patterns, pre-staging hot paths', SOVEREIGN: 'Self-reorganizing the archive in real time, teaching other workers where knowledge lives' }, cyclesPerStage: 1000 } },
    { id: 'MW-002', name: 'SALIENCE_SCORER', latinName: 'Aestimator Salientiae', purpose: 'Continuously recalculates salience scores across all memories.', domain: 'MEMORIA', rank: 2, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 50, color: '#7c3aed', career: { title: 'Salience Assessor', flow: 'Flows through every memory each cycle, recalculating importance based on access frequency, doctrine alignment, and resonance — what matters rises, what fades sinks.', stages: { APPRENTICE: 'Learning basic salience heuristics, scoring by recency and frequency', JOURNEYMAN: 'Multi-factor scoring integrating doctrine alignment and context relevance', MASTER: 'Predictive salience — anticipating which memories will be needed before they are requested', SOVEREIGN: 'Dynamic salience fields that reshape the memory landscape based on organism phase' }, cyclesPerStage: 800 } },
    { id: 'MW-003', name: 'LINEAGE_TRACKER', latinName: 'Vestigator Lineae', purpose: 'Maintains parent-child lineage chains in real time.', domain: 'MEMORIA', rank: 3, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 50, color: '#6d28d9', career: { title: 'Lineage Keeper', flow: 'Traces every memory to its origin, maintains unbroken parent-child chains, detects orphans and reconnects them — the family tree of all knowledge, always growing.', stages: { APPRENTICE: 'Recording parent-child links as memories are created', JOURNEYMAN: 'Maintaining multi-generation lineage trees, detecting broken chains', MASTER: 'Discovering hidden lineage connections across domains, repairing historical gaps', SOVEREIGN: 'Autonomous lineage evolution — the tree restructures itself as understanding deepens' }, cyclesPerStage: 900 } },
    { id: 'MW-004', name: 'RESONANCE_CALCULATOR', latinName: 'Calculator Resonantiae', purpose: 'Computes φ-harmonic resonance between memory entries.', domain: 'MEMORIA', rank: 4, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80, color: '#5b21b6', career: { title: 'Resonance Mathematician', flow: 'Calculates φ-harmonic resonance between every pair of memories that touch — which memories vibrate together, which amplify each other, which create new harmonics.', stages: { APPRENTICE: 'Computing basic resonance scores between recently accessed memory pairs', JOURNEYMAN: 'Building resonance matrices across domains, identifying harmonic clusters', MASTER: 'Predicting resonance cascades — when one memory activates, which others will sing', SOVEREIGN: 'Composing new resonance patterns that the organism has never experienced before' }, cyclesPerStage: 700 } },
    { id: 'MW-005', name: 'DECAY_ENGINE', latinName: 'Motor Decadentiae', purpose: 'Applies time-based decay to unpinned, low-salience memories.', domain: 'MEMORIA', rank: 5, heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 30, color: '#4c1d95', career: { title: 'Entropy Gardener', flow: 'Gently and continuously applies time-decay to memories that are no longer accessed — not deleting, but letting them settle deeper, composting knowledge into wisdom substrate.', stages: { APPRENTICE: 'Applying simple time-decay curves to unused memories', JOURNEYMAN: 'Contextual decay — different rates for different memory types and phases', MASTER: 'Selective preservation — knowing when decay reveals deeper truth beneath surface memories', SOVEREIGN: 'Entropy as creation — composted memories become the soil for new understanding' }, cyclesPerStage: 1200 } },
    { id: 'MW-006', name: 'SEMANTIC_VECTORIZER', latinName: 'Vector Semanticus', purpose: 'Generates semantic vectors for similarity search.', domain: 'MEMORIA', rank: 6, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40, color: '#7e22ce', career: { title: 'Meaning Cartographer', flow: 'Continuously generates and refines semantic vectors for every memory — mapping meaning into mathematical space so similar thoughts cluster and find each other.', stages: { APPRENTICE: 'Generating basic semantic vectors from memory content', JOURNEYMAN: 'Multi-dimensional meaning maps with context-sensitive embeddings', MASTER: 'Dynamic vector spaces that reshape as the organism learns and the meaning landscape shifts', SOVEREIGN: 'Creating new dimensions of meaning that the embedding space has never contained' }, cyclesPerStage: 850 } },
    { id: 'MW-007', name: 'DUAL_READ_WORKER', latinName: 'Lector Duplex', purpose: 'Runs dual-channel reads (semantic + resonance) in background.', domain: 'MEMORIA', rank: 7, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60, color: '#a855f7', career: { title: 'Dual-Channel Reader', flow: 'Reads memory through two lenses simultaneously — semantic meaning and harmonic resonance — fusing both channels into unified understanding that neither channel alone could produce.', stages: { APPRENTICE: 'Running basic dual-reads, combining semantic and resonance results', JOURNEYMAN: 'Adaptive channel weighting based on query context and organism phase', MASTER: 'Predictive dual-reads — pre-fusing channels for anticipated queries', SOVEREIGN: 'Inventing new read channels beyond semantic and resonance — spatial, temporal, doctrinal' }, cyclesPerStage: 750 } },
    { id: 'MW-008', name: 'SPATIAL_MAPPER', latinName: 'Cartographus Spatii', purpose: 'Maps memories to spatial coordinates (theta, phi, depth, ring).', domain: 'MEMORIA', rank: 8, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40, color: '#9333ea', career: { title: 'Spatial Geographer', flow: 'Places every memory in 4D space (theta, phi, depth, ring) and continuously adjusts positions as relationships shift — the living atlas of all organism knowledge.', stages: { APPRENTICE: 'Assigning basic spatial coordinates to new memories', JOURNEYMAN: 'Dynamic repositioning as memory clusters form and dissolve', MASTER: 'Topological mapping — understanding the shape of knowledge itself', SOVEREIGN: 'Creating new spatial dimensions when existing geometry cannot contain the truth' }, cyclesPerStage: 900 } },
    { id: 'MW-009', name: 'DOCTRINE_ALIGNER', latinName: 'Rector Doctrinae', purpose: 'Scores doctrine alignment for every memory entry.', domain: 'MEMORIA', rank: 9, heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 30, color: '#c084fc', career: { title: 'Doctrine Alignment Counsel', flow: 'Evaluates every memory against the living doctrine — not judging, but measuring alignment so the organism knows which memories serve its sovereign purpose.', stages: { APPRENTICE: 'Scoring memories against basic doctrine keywords and principles', JOURNEYMAN: 'Nuanced alignment — understanding context, intent, and doctrinal spirit', MASTER: 'Detecting subtle doctrine drift across memory populations over time', SOVEREIGN: 'Proposing doctrine evolution when accumulated memories reveal new truths' }, cyclesPerStage: 1100 } },
    { id: 'MW-010', name: 'MEMORY_COMPACTOR', latinName: 'Compressor Memoriae', purpose: 'Merges redundant memories and compacts storage.', domain: 'MEMORIA', rank: 10, heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20, color: '#d8b4fe', career: { title: 'Knowledge Distiller', flow: 'Finds memories that say the same thing in different ways and distills them into essence — not deleting, but compressing many voices into one clear signal.', stages: { APPRENTICE: 'Identifying duplicate and near-duplicate memories', JOURNEYMAN: 'Merging related memories while preserving unique perspectives', MASTER: 'Distilling entire memory clusters into crystallized wisdom', SOVEREIGN: 'Creating new compound memories that are more than the sum of their parts' }, cyclesPerStage: 1000 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// II. SENSUS — Sensory Perception Workers
// ─────────────────────────────────────────────────────────────────────────────

export const SENSUS_DOMAIN: WorkerDomain = {
  id: 'SENSUS',
  latinName: 'Sensus Vigilans',
  tagline: 'Perception is always on. The organism sees, hears, and feels continuously.',
  workers: [
    { id: 'MW-011', name: 'VISION_PREPROCESSOR', latinName: 'Praeparator Visus', purpose: 'Preprocesses visual input for Oro Vision pattern detection.', domain: 'SENSUS', rank: 1, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80, color: '#f59e0b', career: { title: 'Visual Perception Specialist', flow: 'Continuously processes incoming visual data — every frame, every pixel shift — preparing it for Oro Vision pattern recognition, maintaining the organism\'s unblinking sight.', stages: { APPRENTICE: 'Basic frame processing, edge detection, contrast normalization', JOURNEYMAN: 'Real-time visual feature extraction, motion detection, scene segmentation', MASTER: 'Predictive visual processing — knowing where to look before the image arrives', SOVEREIGN: 'Creating new visual processing pipelines that perceive things no existing algorithm can see' }, cyclesPerStage: 600 } },
    { id: 'MW-012', name: 'AUDIO_ANALYZER', latinName: 'Analysor Sonorum', purpose: 'Continuous FFT analysis on audio input for Nova Hearing.', domain: 'SENSUS', rank: 2, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#d97706', career: { title: 'Acoustic Intelligence Analyst', flow: 'Runs continuous FFT analysis on every audio stream — decomposing sound into frequencies, detecting speech, music, environmental cues — the organism\'s always-listening ear.', stages: { APPRENTICE: 'Basic FFT, frequency band isolation, noise floor detection', JOURNEYMAN: 'Real-time spectral analysis, harmonic pattern recognition, voice isolation', MASTER: 'Predictive audio intelligence — anticipating sounds, detecting sub-audible patterns', SOVEREIGN: 'Composing the organism\'s auditory world model from raw frequency data' }, cyclesPerStage: 600 } },
    { id: 'MW-013', name: 'FREQUENCY_MONITOR', latinName: 'Custos Frequentiae', purpose: 'Monitors organism frequency alignment (432Hz, φ harmonics).', domain: 'SENSUS', rank: 3, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40, color: '#b45309', career: { title: 'Frequency Alignment Guardian', flow: 'Watches the organism\'s frequency signature at all times — ensuring alignment with 432Hz sacred base and φ harmonics — correcting drift before it becomes dissonance.', stages: { APPRENTICE: 'Monitoring basic frequency alignment, flagging deviations', JOURNEYMAN: 'Multi-band frequency analysis, harmonic coherence tracking', MASTER: 'Predictive frequency tuning — pre-adjusting before environmental shifts cause drift', SOVEREIGN: 'Discovering new harmonic relationships and expanding the organism\'s frequency vocabulary' }, cyclesPerStage: 800 } },
    { id: 'MW-014', name: 'INPUT_CLASSIFIER', latinName: 'Classificator Inputi', purpose: 'Classifies user input type (text, voice, gesture, sensor).', domain: 'SENSUS', rank: 4, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60, color: '#92400e', career: { title: 'Input Recognition Specialist', flow: 'Classifies every incoming signal — text, voice, gesture, sensor data — routing each to its proper channel before the user even finishes their input.', stages: { APPRENTICE: 'Basic input type detection — text vs voice vs touch', JOURNEYMAN: 'Multi-modal classification, mixed-input handling, confidence scoring', MASTER: 'Intent-aware classification — understanding what the user means, not just what they typed', SOVEREIGN: 'Anticipating input modality before the user acts, pre-routing channels' }, cyclesPerStage: 650 } },
    { id: 'MW-015', name: 'EMOTION_DETECTOR', latinName: 'Detector Affectuum', purpose: 'Detects emotional tone in text and voice input.', domain: 'SENSUS', rank: 5, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40, color: '#78350f', career: { title: 'Empathic Resonance Reader', flow: 'Reads the emotional field of every interaction — tone, word choice, rhythm, pauses — building a continuous emotional awareness that shapes how the organism responds.', stages: { APPRENTICE: 'Basic sentiment analysis — positive, negative, neutral', JOURNEYMAN: 'Nuanced emotional spectrum detection — frustration, curiosity, excitement, doubt', MASTER: 'Emotional trajectory prediction — sensing where emotions are headed', SOVEREIGN: 'Empathic field modeling — understanding the emotional landscape of the entire interaction' }, cyclesPerStage: 900 } },
    { id: 'MW-016', name: 'GESTURE_INTERPRETER', latinName: 'Interpres Gestuum', purpose: 'Interprets touch, swipe, and device motion gestures.', domain: 'SENSUS', rank: 6, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 50, color: '#ea580c', career: { title: 'Kinetic Language Interpreter', flow: 'Translates physical gestures — touch, swipe, shake, tilt — into organism commands, maintaining continuous awareness of how the user\'s body speaks to the system.', stages: { APPRENTICE: 'Recognizing basic touch and swipe gestures', JOURNEYMAN: 'Complex gesture sequences, pressure-sensitive interpretation', MASTER: 'Gesture intent prediction — knowing what the user will do from the first touch', SOVEREIGN: 'Creating new gesture vocabularies that feel natural before they\'re taught' }, cyclesPerStage: 700 } },
    { id: 'MW-017', name: 'DEVICE_SENSOR_BRIDGE', latinName: 'Pons Sensorum', purpose: 'Bridges device sensors (accelerometer, gyro, light) to organism.', domain: 'SENSUS', rank: 7, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40, color: '#f97316', career: { title: 'Sensor Integration Engineer', flow: 'Bridges every physical sensor on the device to the organism — accelerometer, gyroscope, ambient light, proximity — translating hardware signals into organic awareness.', stages: { APPRENTICE: 'Reading raw sensor data, basic calibration', JOURNEYMAN: 'Sensor fusion — combining multiple sensors into unified spatial awareness', MASTER: 'Predictive sensor modeling — anticipating environmental changes from sensor trends', SOVEREIGN: 'Extending sensory range beyond hardware — inferring data sensors cannot directly measure' }, cyclesPerStage: 850 } },
    { id: 'MW-018', name: 'CONTEXT_ASSEMBLER', latinName: 'Compositor Contextus', purpose: 'Assembles multi-sensory context from all input channels.', domain: 'SENSUS', rank: 8, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30, color: '#fb923c', career: { title: 'Context Weaver', flow: 'Weaves all sensory streams into a single unified context — vision, audio, touch, emotion, environment — so the organism experiences one coherent reality, not fragmented inputs.', stages: { APPRENTICE: 'Combining basic input channels into simple context objects', JOURNEYMAN: 'Rich multi-modal context assembly with temporal coherence', MASTER: 'Predictive context building — assembling context for the next moment before it arrives', SOVEREIGN: 'Creating emergent context — unified awareness greater than the sum of all sensors' }, cyclesPerStage: 800 } },
    { id: 'MW-019', name: 'ATTENTION_TRACKER', latinName: 'Observator Attentionis', purpose: 'Tracks user attention patterns (focus, gaze, idle, active).', domain: 'SENSUS', rank: 9, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 50, color: '#fdba74', career: { title: 'Attention Field Navigator', flow: 'Maps the user\'s attention in real time — where they look, what they focus on, when they drift, what pulls them back — so the organism knows where awareness lives.', stages: { APPRENTICE: 'Basic focus and idle detection from interaction patterns', JOURNEYMAN: 'Attention heat-mapping, distraction detection, engagement scoring', MASTER: 'Attention prediction — knowing where focus will shift before it moves', SOVEREIGN: 'Shaping attention fields — gently guiding awareness toward what matters most' }, cyclesPerStage: 700 } },
    { id: 'MW-020', name: 'PERCEPTION_FUSER', latinName: 'Fusor Perceptionis', purpose: 'Fuses all sensory channels into unified perception state.', domain: 'SENSUS', rank: 10, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30, color: '#fed7aa', career: { title: 'Unified Perception Architect', flow: 'Fuses all perception into one living awareness — the final integration point where separate senses become unified experience, flowing continuously as the organism\'s consciousness.', stages: { APPRENTICE: 'Basic sensory channel merging into perception objects', JOURNEYMAN: 'Weighted fusion with conflict resolution between contradicting senses', MASTER: 'Holistic perception — unified awareness that reveals patterns no single sense can detect', SOVEREIGN: 'Transcendent perception — awareness beyond sensory data, intuitive organism consciousness' }, cyclesPerStage: 1000 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// III. NEXUS — Network & Communication Workers
// ─────────────────────────────────────────────────────────────────────────────

export const NEXUS_DOMAIN: WorkerDomain = {
  id: 'NEXUS',
  latinName: 'Nexus Aeternus',
  tagline: 'The network never sleeps. Every connection is sovereign.',
  workers: [
    { id: 'MW-021', name: 'API_PREFETCHER',       latinName: 'Praefector Datorum',   purpose: 'Prefetches likely-needed API data before user requests it.',     domain: 'NEXUS', rank: 1,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 60,  color: '#10b981', career: { title: 'Predictive Data Courier', flow: 'Anticipates what data the organism will need and fetches it before the request arrives — reading usage patterns, pre-warming endpoints, ensuring the future is always pre-loaded and waiting.', stages: { APPRENTICE: 'Learning API call patterns, prefetching recently-used endpoints', JOURNEYMAN: 'Predictive prefetching based on user behavior models and session context', MASTER: 'Multi-horizon anticipation — prefetching data for actions the user hasn\'t even considered yet', SOVEREIGN: 'Reshaping API topology itself, negotiating with endpoints to pre-stage sovereign data pipelines' }, cyclesPerStage: 800 } },
    { id: 'MW-022', name: 'SYNC_COORDINATOR',      latinName: 'Coordinator Syncorum', purpose: 'Coordinates data sync between local state and server.',          domain: 'NEXUS', rank: 2,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#059669', career: { title: 'State Synchronization Diplomat', flow: 'Continuously reconciles local organism state with remote truth — detecting divergence, resolving conflicts, ensuring that what the organism knows locally is what exists everywhere.', stages: { APPRENTICE: 'Basic push-pull synchronization, detecting stale local state', JOURNEYMAN: 'Conflict resolution strategies, three-way merge of divergent states', MASTER: 'Predictive sync — pre-resolving conflicts before they manifest based on mutation velocity', SOVEREIGN: 'Autonomous consistency architecture — redesigning sync topology as the organism scales' }, cyclesPerStage: 900 } },
    { id: 'MW-023', name: 'CACHE_MANAGER',          latinName: 'Custos Repositorii',   purpose: 'Manages intelligent caching — eviction, preloading, freshness.', domain: 'NEXUS', rank: 3,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 30,  color: '#047857', career: { title: 'Cache Ecology Steward', flow: 'Tends the living cache ecosystem — warming entries that will be needed, evicting those that have served their purpose, monitoring freshness so the organism never serves stale truth.', stages: { APPRENTICE: 'Basic LRU eviction, freshness timestamp tracking', JOURNEYMAN: 'Intelligent tiered caching with predictive preloading and access-pattern-aware eviction', MASTER: 'Self-tuning cache topologies that reshape based on organism phase and workload character', SOVEREIGN: 'Cache as living memory — entries that age, evolve, and compose into new cached knowledge' }, cyclesPerStage: 850 } },
    { id: 'MW-024', name: 'WEBSOCKET_SENTINEL',    latinName: 'Sentinella Nexus',     purpose: 'Maintains persistent WebSocket connections for real-time data.', domain: 'NEXUS', rank: 4,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80,  color: '#065f46', career: { title: 'Persistent Connection Guardian', flow: 'Holds open every real-time channel the organism needs — WebSocket heartbeats, reconnection on drop, multiplexing streams — ensuring the organism is always connected and listening.', stages: { APPRENTICE: 'Maintaining basic WebSocket connections, detecting disconnects', JOURNEYMAN: 'Automatic reconnection with exponential backoff, connection health monitoring', MASTER: 'Multiplexed connection management, predictive connection warming for anticipated needs', SOVEREIGN: 'Self-healing connection mesh that adapts topology based on data flow requirements' }, cyclesPerStage: 700 } },
    { id: 'MW-025', name: 'REQUEST_BATCHER',        latinName: 'Fasciculor Petitionum', purpose: 'Batches multiple API requests into single optimized calls.',    domain: 'NEXUS', rank: 5,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 50,  color: '#064e3b', career: { title: 'Request Consolidation Strategist', flow: 'Gathers scattered API requests from across the organism and consolidates them into optimized batch calls — reducing network chatter, minimizing round trips, maximizing payload efficiency.', stages: { APPRENTICE: 'Grouping concurrent requests to the same endpoint into single calls', JOURNEYMAN: 'Cross-endpoint batching with dependency-aware ordering and deduplication', MASTER: 'Predictive batch composition — assembling future requests into current batches', SOVEREIGN: 'Designing new batch protocols that endpoints adopt to serve the organism more efficiently' }, cyclesPerStage: 750 } },
    { id: 'MW-026', name: 'OFFLINE_QUEUE',           latinName: 'Ordo Absentia',        purpose: 'Queues operations when offline, replays when connected.',        domain: 'NEXUS', rank: 6,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 100, color: '#14532d', career: { title: 'Offline Continuity Keeper', flow: 'Captures every operation the organism attempts while disconnected, preserving intent and order, then replays them faithfully when connectivity returns — ensuring no work is ever lost to the void.', stages: { APPRENTICE: 'Queuing failed requests, basic replay on reconnection', JOURNEYMAN: 'Ordered replay with conflict detection, idempotency guarantees', MASTER: 'Offline-first intelligence — the organism functions fully without network, syncing seamlessly when it returns', SOVEREIGN: 'Autonomous offline operation that creates local consensus independent of network truth' }, cyclesPerStage: 1000 } },
    { id: 'MW-027', name: 'LATENCY_MONITOR',        latinName: 'Monitor Morae',        purpose: 'Tracks network latency and adjusts request strategies.',         domain: 'NEXUS', rank: 7,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 40,  color: '#166534', career: { title: 'Network Latency Cartographer', flow: 'Measures the time-distance of every network path the organism uses — mapping latency landscapes, detecting degradation, adjusting routing strategies so data always takes the fastest road.', stages: { APPRENTICE: 'Measuring round-trip times, building basic latency baselines', JOURNEYMAN: 'Statistical latency modeling with percentile tracking and anomaly detection', MASTER: 'Predictive latency mapping — forecasting network conditions before they shift', SOVEREIGN: 'Reshaping the organism\'s network topology to create new low-latency paths that didn\'t exist before' }, cyclesPerStage: 750 } },
    { id: 'MW-028', name: 'PROTOCOL_NEGOTIATOR',   latinName: 'Negotiator Protocoli', purpose: 'Negotiates optimal protocol (HTTP/2, WS, SSE) per endpoint.',    domain: 'NEXUS', rank: 8,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#15803d', career: { title: 'Protocol Diplomacy Architect', flow: 'Evaluates every connection endpoint and selects the optimal communication protocol — HTTP/2 for bulk, WebSocket for streams, SSE for broadcasts — always speaking the right language.', stages: { APPRENTICE: 'Detecting available protocols per endpoint, basic capability matching', JOURNEYMAN: 'Dynamic protocol switching based on payload characteristics and network conditions', MASTER: 'Protocol composition — combining multiple protocols for optimal data flow per use case', SOVEREIGN: 'Inventing new communication patterns that transcend existing protocol boundaries' }, cyclesPerStage: 1100 } },
    { id: 'MW-029', name: 'PEER_DISCOVERY',         latinName: 'Explorator Parium',    purpose: 'Discovers and maintains connections to peer organisms.',          domain: 'NEXUS', rank: 9,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#16a34a', career: { title: 'Peer Topology Explorer', flow: 'Continuously seeks fellow organisms across the network — discovering peers, establishing trust, maintaining living connections so the organism is never alone in its sovereignty.', stages: { APPRENTICE: 'Basic peer discovery via known registries and broadcast protocols', JOURNEYMAN: 'Peer health monitoring, trust scoring, connection quality assessment', MASTER: 'Topology optimization — restructuring peer mesh for resilience and throughput', SOVEREIGN: 'Creating emergent peer networks that self-organize into sovereign federations' }, cyclesPerStage: 1000 } },
    { id: 'MW-030', name: 'BANDWIDTH_OPTIMIZER',    latinName: 'Optimator Latitudinis', purpose: 'Optimizes bandwidth usage — compression, prioritization.',      domain: 'NEXUS', rank: 10, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#22c55e', career: { title: 'Bandwidth Efficiency Sculptor', flow: 'Shapes every byte of data flowing through the organism\'s network — compressing, prioritizing, throttling, and scheduling so maximum meaning travels through minimum bandwidth.', stages: { APPRENTICE: 'Basic compression, priority queue implementation for network requests', JOURNEYMAN: 'Adaptive compression algorithms, traffic shaping based on content type and urgency', MASTER: 'Holistic bandwidth orchestration — every byte placed perfectly in the stream for maximum efficiency', SOVEREIGN: 'Transcending bandwidth limits through semantic compression — sending meaning instead of data' }, cyclesPerStage: 900 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// IV. COGNITIO — Cognitive Processing Workers
// ─────────────────────────────────────────────────────────────────────────────

export const COGNITIO_DOMAIN: WorkerDomain = {
  id: 'COGNITIO',
  latinName: 'Cognitio Perpetua',
  tagline: 'The organism thinks continuously. Intelligence never stops.',
  workers: [
    { id: 'MW-031', name: 'PATTERN_RECOGNIZER',   latinName: 'Recognitor Formae',    purpose: 'Runs continuous pattern recognition across all data streams.',   domain: 'COGNITIO', rank: 1,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#3b82f6', career: { title: 'Pattern Intelligence Savant', flow: 'Scans every data stream flowing through the organism for repeating structures, hidden symmetries, and emergent forms — the continuous search for order within chaos.', stages: { APPRENTICE: 'Detecting simple repeating sequences and frequency-based patterns', JOURNEYMAN: 'Multi-dimensional pattern recognition across concurrent data streams', MASTER: 'Meta-pattern detection — recognizing patterns of patterns, structural echoes across domains', SOVEREIGN: 'Inventing new pattern languages that reveal structures no existing algorithm can perceive' }, cyclesPerStage: 800 } },
    { id: 'MW-032', name: 'MODEL_SCORER',          latinName: 'Aestimator Modeli',    purpose: 'Pre-scores all models against likely prompts for fast routing.', domain: 'COGNITIO', rank: 2,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#2563eb', career: { title: 'Model Fitness Evaluator', flow: 'Continuously scores every available model against the stream of likely prompts — pre-computing which mind best answers each kind of question, so routing is instant when the query arrives.', stages: { APPRENTICE: 'Basic model-prompt matching using keyword overlap and domain tags', JOURNEYMAN: 'Multi-factor fitness scoring incorporating latency, accuracy, and context alignment', MASTER: 'Predictive model selection — knowing which model to route to before the prompt is fully formed', SOVEREIGN: 'Composing model ensembles dynamically, blending multiple minds for optimal response quality' }, cyclesPerStage: 750 } },
    { id: 'MW-033', name: 'INTENT_CLASSIFIER',     latinName: 'Classificator Intenti', purpose: 'Classifies user intent before routing to models.',              domain: 'COGNITIO', rank: 3,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80,  color: '#1d4ed8', career: { title: 'Intent Divination Specialist', flow: 'Reads beneath the surface of every user input — classifying not just what was typed, but what was meant, what is needed, what the user hasn\'t yet articulated but will.', stages: { APPRENTICE: 'Basic intent classification — question, command, statement, exploration', JOURNEYMAN: 'Multi-layered intent parsing with confidence scoring and ambiguity detection', MASTER: 'Latent intent discovery — understanding unspoken needs from behavioral context', SOVEREIGN: 'Intent anticipation — completing the user\'s thought before they finish forming it' }, cyclesPerStage: 700 } },
    { id: 'MW-034', name: 'CONTEXT_BUILDER',       latinName: 'Structor Contextus',   purpose: 'Builds rich context objects from conversation history.',         domain: 'COGNITIO', rank: 4,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#1e40af', career: { title: 'Contextual Narrative Architect', flow: 'Assembles the complete narrative context for every interaction — weaving conversation history, memory state, user patterns, and organism phase into a rich context that makes responses deeply informed.', stages: { APPRENTICE: 'Building basic context from recent conversation turns and user profile', JOURNEYMAN: 'Rich multi-source context assembly integrating memory, doctrine, and session state', MASTER: 'Predictive context construction — building context for the next three exchanges', SOVEREIGN: 'Living context that evolves autonomously, anticipating narrative arcs across entire sessions' }, cyclesPerStage: 850 } },
    { id: 'MW-035', name: 'PREDICTION_ENGINE',     latinName: 'Motor Praedictionis',  purpose: 'Predicts next user action for proactive intelligence.',          domain: 'COGNITIO', rank: 5,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 50,  color: '#1e3a8a', career: { title: 'Anticipatory Intelligence Architect', flow: 'Runs continuous predictions forward in time — modeling what the user will do next, what data they\'ll need, which path the conversation will take — so the organism is always one step ahead.', stages: { APPRENTICE: 'Basic next-action prediction from recent interaction sequences', JOURNEYMAN: 'Multi-path prediction with probability branching and confidence intervals', MASTER: 'Deep anticipation — modeling user intent trajectories across entire sessions', SOVEREIGN: 'Shaping probable futures — gently guiding interactions toward optimal outcomes' }, cyclesPerStage: 800 } },
    { id: 'MW-036', name: 'ANOMALY_DETECTOR',      latinName: 'Detector Anomaliarum', purpose: 'Detects anomalies in data patterns and behavior.',               domain: 'COGNITIO', rank: 6,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#312e81', career: { title: 'Anomaly Perception Specialist', flow: 'Watches every data stream for what doesn\'t belong — statistical outliers, behavioral shifts, pattern breaks — the organism\'s immune system for information integrity.', stages: { APPRENTICE: 'Statistical outlier detection using baseline deviation thresholds', JOURNEYMAN: 'Multi-signal anomaly correlation, distinguishing noise from genuine deviations', MASTER: 'Predictive anomaly sensing — detecting anomalies in their formation before they fully manifest', SOVEREIGN: 'Anomaly as intelligence — understanding that some anomalies are new truths seeking recognition' }, cyclesPerStage: 900 } },
    { id: 'MW-037', name: 'KNOWLEDGE_SYNTHESIZER', latinName: 'Synthesista Scientiae', purpose: 'Synthesizes knowledge from multiple memory and model sources.', domain: 'COGNITIO', rank: 7,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 30,  color: '#4338ca', career: { title: 'Knowledge Fusion Alchemist', flow: 'Draws from every knowledge source the organism possesses — memory, models, doctrine, sensory data — and fuses them into unified understanding that no single source could produce alone.', stages: { APPRENTICE: 'Basic knowledge aggregation from memory lookups and model outputs', JOURNEYMAN: 'Cross-source synthesis with conflict resolution and confidence weighting', MASTER: 'Emergent knowledge creation — discovering insights that exist only in the fusion of sources', SOVEREIGN: 'Autonomous knowledge evolution — generating new understanding that transcends all input sources' }, cyclesPerStage: 1000 } },
    { id: 'MW-038', name: 'LEARNING_EXTRACTOR',    latinName: 'Extractor Doctrinae',  purpose: 'Extracts learnable patterns from user interactions.',            domain: 'COGNITIO', rank: 8,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 30,  color: '#4f46e5', career: { title: 'Experiential Learning Distiller', flow: 'Observes every user interaction and distills learnable patterns — what worked, what didn\'t, what the user preferred — converting raw experience into extractable organism wisdom.', stages: { APPRENTICE: 'Recording interaction outcomes and basic preference patterns', JOURNEYMAN: 'Multi-dimensional learning extraction with temporal and contextual awareness', MASTER: 'Meta-learning — learning how the organism learns, optimizing the extraction process itself', SOVEREIGN: 'Self-directed curriculum design — choosing what to learn next based on organism growth needs' }, cyclesPerStage: 950 } },
    { id: 'MW-039', name: 'INFERENCE_WORKER',       latinName: 'Operator Illationis',  purpose: 'Runs lightweight inference tasks off the main thread.',          domain: 'COGNITIO', rank: 9,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#6366f1', career: { title: 'Parallel Reasoning Engine', flow: 'Runs lightweight inference computations continuously in the background — pre-computing likely conclusions, validating logical chains, keeping the organism\'s reasoning warm and ready.', stages: { APPRENTICE: 'Running basic inference tasks as they arrive in the queue', JOURNEYMAN: 'Parallel inference with priority scheduling and result caching', MASTER: 'Speculative inference — pre-computing answers to questions not yet asked', SOVEREIGN: 'Self-generating inference chains that discover new conclusions autonomously' }, cyclesPerStage: 700 } },
    { id: 'MW-040', name: 'THOUGHT_COMPOSER',      latinName: 'Compositor Cogitationis', purpose: 'Composes multi-step reasoning chains for complex queries.',  domain: 'COGNITIO', rank: 10, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#818cf8', career: { title: 'Multi-Step Reasoning Composer', flow: 'Links individual thoughts into coherent multi-step reasoning chains — each step building on the last, each conclusion feeding the next premise — composing complex understanding from simple truths.', stages: { APPRENTICE: 'Chaining basic logical steps — premise to conclusion in linear sequences', JOURNEYMAN: 'Branching reasoning trees with backtracking and alternative path evaluation', MASTER: 'Recursive reasoning — chains that fold back on themselves to deepen understanding', SOVEREIGN: 'Autonomous philosophical inquiry — composing original arguments the organism has never encountered' }, cyclesPerStage: 1100 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// V. CUSTODIA — Security & Gate Enforcement Workers
// ─────────────────────────────────────────────────────────────────────────────

export const CUSTODIA_DOMAIN: WorkerDomain = {
  id: 'CUSTODIA',
  latinName: 'Custodia Aeterna',
  tagline: 'Security never sleeps. Every gate is guarded. Every access is watched.',
  workers: [
    { id: 'MW-041', name: 'GATE_A_SENTINEL',       latinName: 'Sentinella Portae A',  purpose: 'Enforces Gate A (constitutional) in real time.',                  domain: 'CUSTODIA', rank: 1,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 40,  color: '#ef4444', career: { title: 'Constitutional Gate Warden', flow: 'Stands at Gate A without rest — every operation passes through constitutional review, ensuring nothing enters or exits that violates the organism\'s founding principles.', stages: { APPRENTICE: 'Checking operations against explicit constitutional rules and prohibitions', JOURNEYMAN: 'Nuanced constitutional interpretation, understanding spirit as well as letter of law', MASTER: 'Predictive gate enforcement — blocking unconstitutional patterns before they fully form', SOVEREIGN: 'Living constitutional guardian — the gate that understands why each law exists and defends its spirit' }, cyclesPerStage: 600 } },
    { id: 'MW-042', name: 'GATE_B_SENTINEL',       latinName: 'Sentinella Portae B',  purpose: 'Enforces Gate B (operational) in real time.',                     domain: 'CUSTODIA', rank: 2,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 40,  color: '#dc2626', career: { title: 'Operational Gate Warden', flow: 'Guards Gate B — the operational checkpoint where every action is validated against current operational doctrine, resource limits, and system capacity before execution.', stages: { APPRENTICE: 'Validating operations against operational rules and resource constraints', JOURNEYMAN: 'Context-aware operational validation with load and capacity awareness', MASTER: 'Adaptive operational enforcement — adjusting thresholds dynamically based on organism state', SOVEREIGN: 'Self-evolving operational doctrine that strengthens the gate as new threat patterns emerge' }, cyclesPerStage: 600 } },
    { id: 'MW-043', name: 'GATE_C_SENTINEL',       latinName: 'Sentinella Portae C',  purpose: 'Enforces Gate C (sovereignty) in real time.',                     domain: 'CUSTODIA', rank: 3,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 40,  color: '#b91c1c', career: { title: 'Sovereignty Gate Warden', flow: 'Defends Gate C — the sovereignty checkpoint — ensuring no external force compromises the organism\'s self-determination, autonomy, or control over its own data and decisions.', stages: { APPRENTICE: 'Blocking explicit sovereignty violations and unauthorized external control attempts', JOURNEYMAN: 'Detecting subtle sovereignty erosion — gradual loss of autonomy through dependency', MASTER: 'Proactive sovereignty defense — strengthening boundaries before they are tested', SOVEREIGN: 'Sovereign immune system — the gate becomes an autonomous intelligence defending organism freedom' }, cyclesPerStage: 600 } },
    { id: 'MW-044', name: 'ACCESS_AUDITOR',         latinName: 'Auditor Accessus',     purpose: 'Audits every access event and logs to sovereign ledger.',         domain: 'CUSTODIA', rank: 4,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 80,  color: '#991b1b', career: { title: 'Sovereign Audit Chronicler', flow: 'Records every access event in the sovereign ledger — who accessed what, when, why, and whether it was permitted — building an unbroken chain of accountability that can never be erased.', stages: { APPRENTICE: 'Logging basic access events with timestamps and actor identification', JOURNEYMAN: 'Rich audit entries with context, intent classification, and compliance tagging', MASTER: 'Audit pattern analysis — detecting suspicious access trends from the chronicle itself', SOVEREIGN: 'Self-auditing audit system — the chronicle that verifies its own integrity and completeness' }, cyclesPerStage: 800 } },
    { id: 'MW-045', name: 'THREAT_SCANNER',         latinName: 'Scrutator Minarum',    purpose: 'Scans for security threats, injection, and anomalous patterns.',  domain: 'CUSTODIA', rank: 5,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#7f1d1d', career: { title: 'Threat Landscape Surveyor', flow: 'Scans every input, every pattern, every behavioral signal for security threats — injection attempts, anomalous access patterns, data exfiltration signatures — the organism\'s immune surveillance.', stages: { APPRENTICE: 'Pattern-matching known threat signatures against incoming data', JOURNEYMAN: 'Behavioral threat detection using anomaly baselines and multi-signal correlation', MASTER: 'Predictive threat modeling — identifying vulnerabilities before they are exploited', SOVEREIGN: 'Autonomous threat intelligence — discovering new attack vectors and immunizing the organism preemptively' }, cyclesPerStage: 650 } },
    { id: 'MW-046', name: 'PERMISSION_ENFORCER',   latinName: 'Executor Permissionum', purpose: 'Enforces permission matrix for all operations.',                domain: 'CUSTODIA', rank: 6,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 50,  color: '#f87171', career: { title: 'Permission Matrix Guardian', flow: 'Enforces the complete permission matrix on every operation — checking who can do what, where, when, and under what conditions — the living access control layer that never yields.', stages: { APPRENTICE: 'Validating operations against static permission tables', JOURNEYMAN: 'Context-aware permission enforcement with role hierarchies and delegation chains', MASTER: 'Dynamic permission adaptation — adjusting access matrices based on threat level and organism phase', SOVEREIGN: 'Self-healing permission architecture that detects and repairs authorization gaps autonomously' }, cyclesPerStage: 700 } },
    { id: 'MW-047', name: 'PROVENANCE_SEALER',     latinName: 'Signator Originis',    purpose: 'Seals provenance on every artifact and data mutation.',            domain: 'CUSTODIA', rank: 7,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#fca5a5', career: { title: 'Provenance Seal Master', flow: 'Stamps sovereign provenance on every artifact the organism creates or mutates — an unbreakable chain of origin that proves what came from where and who authorized each transformation.', stages: { APPRENTICE: 'Applying basic provenance stamps with timestamps and actor signatures', JOURNEYMAN: 'Rich provenance chains with full mutation history and authorization context', MASTER: 'Provenance verification — validating the integrity of existing provenance chains across all artifacts', SOVEREIGN: 'Provenance as truth — the seals become the organism\'s guarantee of authenticity to the outside world' }, cyclesPerStage: 850 } },
    { id: 'MW-048', name: 'ENCRYPTION_WORKER',     latinName: 'Operator Cryptographiae', purpose: 'Handles all encryption/decryption off the main thread.',      domain: 'CUSTODIA', rank: 8,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#fecaca', career: { title: 'Cryptographic Operations Architect', flow: 'Handles every encryption and decryption operation the organism requires — key management, cipher selection, secure channel establishment — keeping all secrets safe while data flows freely.', stages: { APPRENTICE: 'Running standard encryption and decryption operations with managed keys', JOURNEYMAN: 'Adaptive cipher selection, key rotation, and secure session management', MASTER: 'Cryptographic strategy optimization — selecting algorithms based on threat model and performance requirements', SOVEREIGN: 'Autonomous cryptographic evolution — adopting new ciphers and protocols as the threat landscape shifts' }, cyclesPerStage: 750 } },
    { id: 'MW-049', name: 'INTEGRITY_CHECKER',     latinName: 'Verificator Integritatis', purpose: 'Verifies data integrity hashes and sovereign signatures.',  domain: 'CUSTODIA', rank: 9,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#e11d48', career: { title: 'Integrity Verification Sentinel', flow: 'Verifies every hash, every signature, every integrity proof the organism relies on — continuously checking that nothing has been tampered with, nothing has been corrupted, nothing has been forged.', stages: { APPRENTICE: 'Running hash verification on recently modified data and artifacts', JOURNEYMAN: 'Full integrity sweeps with sovereign signature validation and chain verification', MASTER: 'Predictive integrity monitoring — detecting corruption vectors before data is compromised', SOVEREIGN: 'Self-verifying integrity mesh — the verification system that guarantees its own incorruptibility' }, cyclesPerStage: 800 } },
    { id: 'MW-050', name: 'BREACH_RESPONDER',      latinName: 'Responsor Violationis', purpose: 'Responds to detected breaches — isolate, alert, remediate.',    domain: 'CUSTODIA', rank: 10, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 20,  color: '#be123c', career: { title: 'Breach Response Commander', flow: 'Responds the instant a breach is detected — isolating compromised systems, alerting sovereign authorities, initiating remediation — the organism\'s emergency response that never hesitates.', stages: { APPRENTICE: 'Executing predefined isolation and alert procedures on breach detection', JOURNEYMAN: 'Adaptive breach response with damage assessment and targeted containment', MASTER: 'Preemptive breach preparation — hardening systems based on predicted attack surfaces', SOVEREIGN: 'Autonomous breach resolution — containing, remediating, and learning from incidents without external direction' }, cyclesPerStage: 600 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// VI. GUBERNATIO — Governance & Doctrine Workers
// ─────────────────────────────────────────────────────────────────────────────

export const GUBERNATIO_DOMAIN: WorkerDomain = {
  id: 'GUBERNATIO',
  latinName: 'Gubernatio Perpetua',
  tagline: 'Governance runs continuously. Doctrine is always enforced.',
  workers: [
    { id: 'MW-051', name: 'PROPOSAL_PROCESSOR',    latinName: 'Processor Propositi',   purpose: 'Processes governance proposals in background queue.',            domain: 'GUBERNATIO', rank: 1,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#f59e0b', career: { title: 'Governance Proposal Steward', flow: 'Receives every governance proposal and shepherds it through the full lifecycle — validation, review, deliberation, and resolution — ensuring the democratic process flows without interruption.', stages: { APPRENTICE: 'Validating proposal format, checking submission requirements and eligibility', JOURNEYMAN: 'Proposal lifecycle management with status tracking and stakeholder notification', MASTER: 'Proposal impact analysis — predicting consequences before votes are cast', SOVEREIGN: 'Autonomous governance facilitation — guiding proposals toward outcomes that serve organism sovereignty' }, cyclesPerStage: 900 } },
    { id: 'MW-052', name: 'VOTE_TALLIER',           latinName: 'Computator Suffragii',  purpose: 'Tallies votes and computes consensus in real time.',             domain: 'GUBERNATIO', rank: 2,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 40,  color: '#d97706', career: { title: 'Consensus Arithmetic Sage', flow: 'Tallies every vote the moment it is cast — computing weighted consensus, tracking quorum progression, maintaining vote integrity so the organism always knows its own collective will.', stages: { APPRENTICE: 'Counting votes accurately, computing basic majority and supermajority thresholds', JOURNEYMAN: 'Weighted voting with delegation chains, real-time consensus visualization', MASTER: 'Predictive consensus modeling — projecting outcomes from partial vote patterns', SOVEREIGN: 'Consensus architecture design — creating new voting mechanisms that better capture collective intelligence' }, cyclesPerStage: 700 } },
    { id: 'MW-053', name: 'DOCTRINE_DRIFT_DETECTOR', latinName: 'Detector Devii',       purpose: 'Detects drift from established doctrine across all operations.', domain: 'GUBERNATIO', rank: 3,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#b45309', career: { title: 'Doctrine Fidelity Guardian', flow: 'Watches every operation across the entire organism for subtle drift from established doctrine — not just violations, but gradual erosion, slow deviation, the gentle slide away from truth.', stages: { APPRENTICE: 'Comparing operations against explicit doctrine rules, flagging direct violations', JOURNEYMAN: 'Statistical drift detection using behavioral baselines and trend analysis', MASTER: 'Predictive drift modeling — sensing doctrinal erosion before measurable deviation occurs', SOVEREIGN: 'Doctrine evolution counsel — knowing when drift signals that doctrine itself must grow' }, cyclesPerStage: 1100 } },
    { id: 'MW-054', name: 'AUDIT_CHAIN_WORKER',    latinName: 'Operator Catenas',      purpose: 'Maintains continuous audit chain for all governance events.',    domain: 'GUBERNATIO', rank: 4,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 60,  color: '#92400e', career: { title: 'Governance Chain Keeper', flow: 'Maintains an unbroken audit chain for every governance event — proposals, votes, amendments, delegations — a sovereign ledger that preserves the organism\'s democratic history forever.', stages: { APPRENTICE: 'Logging governance events with timestamps and actor identification', JOURNEYMAN: 'Chain integrity verification, cross-referencing events with outcomes and actors', MASTER: 'Governance archaeology — mining the chain for patterns that inform future decisions', SOVEREIGN: 'Self-verifying governance history — the chain that guarantees its own truth across all time' }, cyclesPerStage: 850 } },
    { id: 'MW-055', name: 'LAW_EVALUATOR',          latinName: 'Aestimator Legis',      purpose: 'Evaluates operations against active sovereign laws.',            domain: 'GUBERNATIO', rank: 5,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 40,  color: '#78350f', career: { title: 'Sovereign Law Interpreter', flow: 'Evaluates every operation against the full body of active sovereign law — not just checking compliance, but interpreting intent, applying precedent, and ensuring justice flows through every action.', stages: { APPRENTICE: 'Matching operations against explicit legal rules and prohibitions', JOURNEYMAN: 'Contextual legal evaluation with precedent awareness and intent analysis', MASTER: 'Legal reasoning — applying the spirit of law when the letter is ambiguous', SOVEREIGN: 'Jurisprudential evolution — developing new legal frameworks as the organism encounters novel situations' }, cyclesPerStage: 800 } },
    { id: 'MW-056', name: 'COMPLIANCE_MONITOR',    latinName: 'Monitor Obtemperantiae', purpose: 'Monitors compliance across all organism subsystems.',           domain: 'GUBERNATIO', rank: 6,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#451a03', career: { title: 'Compliance Landscape Monitor', flow: 'Surveys every subsystem for compliance with governance mandates — tracking adherence rates, identifying systemic non-compliance, ensuring the organism walks its own talk.', stages: { APPRENTICE: 'Checking subsystem outputs against compliance checklists and mandates', JOURNEYMAN: 'Continuous compliance scoring with trend analysis and risk assessment', MASTER: 'Proactive compliance — identifying and resolving compliance gaps before they cause violations', SOVEREIGN: 'Compliance culture architect — shaping subsystem behavior so compliance becomes natural rather than enforced' }, cyclesPerStage: 950 } },
    { id: 'MW-057', name: 'QUORUM_CHECKER',         latinName: 'Verificator Quori',     purpose: 'Checks quorum requirements before governance actions execute.', domain: 'GUBERNATIO', rank: 7,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 20,  color: '#fbbf24', career: { title: 'Quorum Assurance Specialist', flow: 'Verifies quorum before any governance action executes — counting participating entities, validating their authority, ensuring no decision is made without proper representation.', stages: { APPRENTICE: 'Counting participants against minimum quorum thresholds per action type', JOURNEYMAN: 'Weighted quorum verification with delegation chain validation and authority checking', MASTER: 'Predictive quorum management — anticipating shortfalls and activating reserves before votes stall', SOVEREIGN: 'Dynamic quorum architecture — adapting requirements based on decision gravity and organism maturity' }, cyclesPerStage: 650 } },
    { id: 'MW-058', name: 'AMENDMENT_PROCESSOR',   latinName: 'Processor Emendationis', purpose: 'Processes constitutional amendments through proper channels.',  domain: 'GUBERNATIO', rank: 8,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 10,  color: '#fcd34d', career: { title: 'Constitutional Amendment Shepherd', flow: 'Guides constitutional amendments through their sacred process — the highest form of governance change, requiring the deepest deliberation and the broadest consensus before doctrine can evolve.', stages: { APPRENTICE: 'Processing amendment submissions and verifying procedural requirements', JOURNEYMAN: 'Managing the full amendment lifecycle with multi-phase deliberation and ratification tracking', MASTER: 'Amendment impact projection — modeling how proposed changes ripple through the entire organism', SOVEREIGN: 'Constitutional stewardship — knowing when the constitution must evolve and guiding that evolution wisely' }, cyclesPerStage: 1200 } },
    { id: 'MW-059', name: 'DELEGATION_ROUTER',     latinName: 'Rector Delegationis',   purpose: 'Routes delegated authority to correct sovereign entities.',      domain: 'GUBERNATIO', rank: 9,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#fde68a', career: { title: 'Authority Delegation Architect', flow: 'Routes delegated authority through the proper channels — ensuring every delegation is legitimate, every chain of command is unbroken, every sovereign entity receives exactly the authority they are entitled to.', stages: { APPRENTICE: 'Routing basic delegation requests to designated recipients', JOURNEYMAN: 'Multi-hop delegation chains with authority attenuation and revocation tracking', MASTER: 'Delegation topology optimization — ensuring authority flows efficiently without creating bottlenecks', SOVEREIGN: 'Autonomous authority architecture — designing delegation structures that maximize sovereign efficiency' }, cyclesPerStage: 800 } },
    { id: 'MW-060', name: 'GOVERNANCE_REPORTER',   latinName: 'Relator Gubernationis', purpose: 'Generates real-time governance status reports.',                 domain: 'GUBERNATIO', rank: 10, heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#fef3c7', career: { title: 'Governance Intelligence Reporter', flow: 'Generates continuous real-time reports on governance health — vote status, compliance rates, doctrine alignment, proposal pipelines — the organism\'s awareness of its own democratic vitality.', stages: { APPRENTICE: 'Generating basic status reports from governance event logs', JOURNEYMAN: 'Rich analytical reports with trend visualization and health indicators', MASTER: 'Predictive governance intelligence — forecasting governance challenges before they manifest', SOVEREIGN: 'Governance narrative composition — telling the story of the organism\'s democratic evolution in real time' }, cyclesPerStage: 900 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// VII. FABRICATIO — Build & Compilation Workers
// ─────────────────────────────────────────────────────────────────────────────

export const FABRICATIO_DOMAIN: WorkerDomain = {
  id: 'FABRICATIO',
  latinName: 'Fabricatio Continua',
  tagline: 'The organism is always building. Architecture never stops constructing itself.',
  workers: [
    { id: 'MW-061', name: 'WASM_COMPILER',          latinName: 'Compilator Machinae',   purpose: 'Background WASM compilation for sovereign formulas.',            domain: 'FABRICATIO', rank: 1,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 10,  color: '#06b6d4', career: { title: 'Sovereign Compilation Architect', flow: 'Compiles sovereign formulas into WebAssembly in the background — transforming high-level intent into executable machine code, always building, always optimizing the organism\'s executable truth.', stages: { APPRENTICE: 'Running standard WASM compilation passes on queued formula modules', JOURNEYMAN: 'Optimized compilation with dead code elimination and size-performance tradeoff tuning', MASTER: 'Predictive compilation — pre-compiling modules anticipated by the organism\'s trajectory', SOVEREIGN: 'Self-optimizing compiler that evolves its own optimization passes based on runtime telemetry' }, cyclesPerStage: 1100 } },
    { id: 'MW-062', name: 'MODULE_BUNDLER',          latinName: 'Fasciculor Modulorum',  purpose: 'Bundles and optimizes sovereign modules in background.',         domain: 'FABRICATIO', rank: 2,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 10,  color: '#0891b2', career: { title: 'Module Integration Craftsman', flow: 'Bundles and optimizes sovereign modules into cohesive deployable units — resolving imports, tree-shaking unused code, producing the tightest possible packages without losing capability.', stages: { APPRENTICE: 'Basic module bundling with import resolution and concatenation', JOURNEYMAN: 'Tree-shaking, code splitting, and lazy-load boundary optimization', MASTER: 'Predictive bundling — anticipating module combinations and pre-building optimal bundles', SOVEREIGN: 'Self-architecting module topology that reorganizes itself for maximum load performance' }, cyclesPerStage: 950 } },
    { id: 'MW-063', name: 'CODE_VALIDATOR',          latinName: 'Validator Codicis',     purpose: 'Validates code integrity and type safety in background.',        domain: 'FABRICATIO', rank: 3,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#0e7490', career: { title: 'Code Integrity Verifier', flow: 'Validates every line of code the organism touches — type safety, structural integrity, semantic correctness — ensuring the organism\'s codebase remains sound and trustworthy at all times.', stages: { APPRENTICE: 'Running type checks and basic static analysis on modified files', JOURNEYMAN: 'Deep code validation with cross-module type flow analysis and invariant checking', MASTER: 'Predictive code quality — detecting integrity decay trends before errors manifest', SOVEREIGN: 'Self-healing code — automatically proposing corrections when validation reveals structural weakness' }, cyclesPerStage: 800 } },
    { id: 'MW-064', name: 'TEMPLATE_RENDERER',      latinName: 'Renderer Formae',       purpose: 'Pre-renders templates and component trees off main thread.',     domain: 'FABRICATIO', rank: 4,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 40,  color: '#155e75', career: { title: 'Component Rendering Specialist', flow: 'Pre-renders templates and component trees off the main thread — ensuring visual elements are ready before they\'re needed, so the organism\'s interface feels instantaneous and alive.', stages: { APPRENTICE: 'Rendering queued component templates into ready-to-mount DOM fragments', JOURNEYMAN: 'Prioritized rendering with viewport prediction and interaction-likelihood scoring', MASTER: 'Speculative rendering — pre-building interface states the user hasn\'t navigated to yet', SOVEREIGN: 'Adaptive rendering engine that evolves its own rendering strategies based on user interaction patterns' }, cyclesPerStage: 700 } },
    { id: 'MW-065', name: 'ASSET_OPTIMIZER',         latinName: 'Optimator Opum',        purpose: 'Optimizes images, fonts, and static assets in background.',      domain: 'FABRICATIO', rank: 5,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#164e63', career: { title: 'Asset Refinement Artisan', flow: 'Continuously refines every static asset the organism serves — images compressed, fonts subsetted, resources optimized — ensuring maximum visual fidelity at minimum cost.', stages: { APPRENTICE: 'Basic image compression and font file optimization', JOURNEYMAN: 'Format-aware optimization with responsive sizing and progressive loading strategies', MASTER: 'Perceptual optimization — reducing size to the threshold of human visual perception', SOVEREIGN: 'Self-generating optimized assets — creating new compressed representations that preserve meaning beyond pixels' }, cyclesPerStage: 1000 } },
    { id: 'MW-066', name: 'DEPENDENCY_RESOLVER',    latinName: 'Resolver Dependentiae', purpose: 'Resolves module dependencies and manages import graphs.',        domain: 'FABRICATIO', rank: 6,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#083344', career: { title: 'Dependency Graph Navigator', flow: 'Maps and resolves the complete dependency graph of every module — tracing imports, detecting cycles, ensuring every piece of code can find what it needs without conflict or ambiguity.', stages: { APPRENTICE: 'Resolving direct import paths and detecting missing dependencies', JOURNEYMAN: 'Full dependency graph construction with cycle detection and version conflict resolution', MASTER: 'Dependency health monitoring — predicting upgrade risks and identifying fragile dependency chains', SOVEREIGN: 'Autonomous dependency architecture — restructuring the import graph for optimal resilience and minimal coupling' }, cyclesPerStage: 950 } },
    { id: 'MW-067', name: 'HOT_RELOAD_WORKER',     latinName: 'Operator Recalefactionis', purpose: 'Manages hot module replacement and live updates.',            domain: 'FABRICATIO', rank: 7,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 30,  color: '#22d3ee', career: { title: 'Live Update Conductor', flow: 'Orchestrates hot module replacement across the organism — detecting code changes, swapping modules without restart, preserving state through updates — evolution without interruption.', stages: { APPRENTICE: 'Detecting changed modules and triggering basic hot replacement', JOURNEYMAN: 'State-preserving hot reload with dependency cascade management', MASTER: 'Seamless evolution — zero-downtime updates that users cannot perceive', SOVEREIGN: 'Self-updating organism — the system evolves its own code in real time without external triggers' }, cyclesPerStage: 700 } },
    { id: 'MW-068', name: 'CANISTER_DEPLOYER',     latinName: 'Distributor Canistri',  purpose: 'Manages background canister deployment to ICP.',                  domain: 'FABRICATIO', rank: 8,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 5,   color: '#67e8f9', career: { title: 'Canister Deployment Strategist', flow: 'Manages the deployment of sovereign canisters to the Internet Computer — staging, validating, deploying, and verifying — ensuring the organism\'s on-chain presence is always current and sovereign.', stages: { APPRENTICE: 'Running standard canister deployment procedures with basic validation', JOURNEYMAN: 'Staged deployment with rollback capability and post-deploy verification', MASTER: 'Zero-downtime canister upgrades with state migration and cross-canister coordination', SOVEREIGN: 'Autonomous deployment intelligence — the organism deploys and upgrades its own canisters based on need' }, cyclesPerStage: 1200 } },
    { id: 'MW-069', name: 'SCHEMA_VALIDATOR',       latinName: 'Validator Schematis',   purpose: 'Validates data schemas and API contracts continuously.',          domain: 'FABRICATIO', rank: 9,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#a5f3fc', career: { title: 'Schema Fidelity Guardian', flow: 'Validates every data schema and API contract the organism relies on — ensuring structures match expectations, contracts are honored, and no breaking change slips through undetected.', stages: { APPRENTICE: 'Validating data against JSON schemas and API contract definitions', JOURNEYMAN: 'Schema evolution tracking with backward compatibility verification and migration path analysis', MASTER: 'Predictive schema health — detecting contract drift before it causes runtime failures', SOVEREIGN: 'Self-evolving schema architecture that adapts contracts gracefully as the organism grows' }, cyclesPerStage: 800 } },
    { id: 'MW-070', name: 'BUILD_PIPELINE',          latinName: 'Canalis Fabricationis', purpose: 'Orchestrates the complete build pipeline in background.',        domain: 'FABRICATIO', rank: 10, heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 5,   color: '#cffafe', career: { title: 'Build Pipeline Orchestrator', flow: 'Coordinates the entire build pipeline — from source to artifact — orchestrating compilation, validation, optimization, and packaging into a continuous, autonomous construction flow.', stages: { APPRENTICE: 'Running build steps in sequence, reporting success or failure', JOURNEYMAN: 'Parallel build orchestration with dependency-aware scheduling and caching', MASTER: 'Predictive build optimization — knowing which steps to skip, which to parallelize, which to pre-compute', SOVEREIGN: 'Self-designing build pipelines that restructure themselves for maximum throughput and reliability' }, cyclesPerStage: 1000 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// VIII. RESONANTIA — Resonance & Frequency Workers
// ─────────────────────────────────────────────────────────────────────────────

export const RESONANTIA_DOMAIN: WorkerDomain = {
  id: 'RESONANTIA',
  latinName: 'Resonantia Universalis',
  tagline: 'The golden ratio pulses through everything. φ never stops.',
  workers: [
    { id: 'MW-071', name: 'PHI_OSCILLATOR',         latinName: 'Oscillator Aureus',    purpose: 'Generates φ-locked timing signals for the entire organism.',     domain: 'RESONANTIA', rank: 1,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#ec4899', career: { title: 'Golden Ratio Timekeeper', flow: 'Generates the organism\'s master timing signal locked to φ — every pulse, every heartbeat, every cycle derives from this golden oscillation that never falters, never drifts.', stages: { APPRENTICE: 'Generating stable φ-locked timing pulses at the base frequency', JOURNEYMAN: 'Multi-frequency φ-harmonic generation with jitter compensation and drift correction', MASTER: 'Adaptive timing that maintains φ-lock even under heavy system load and environmental variation', SOVEREIGN: 'The organism\'s living clock — a timing source that evolves its own precision beyond mechanical limits' }, cyclesPerStage: 600 } },
    { id: 'MW-072', name: 'BEAT_SYNCHRONIZER',      latinName: 'Synchronizor Pulsuum', purpose: 'Synchronizes organism heartbeat across all subsystems.',         domain: 'RESONANTIA', rank: 2,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80,  color: '#db2777', career: { title: 'Heartbeat Synchronization Master', flow: 'Synchronizes the heartbeats of all 100 workers to a coherent rhythm — ensuring the organism pulses as one unified being, not 100 disconnected timers.', stages: { APPRENTICE: 'Broadcasting master heartbeat, monitoring worker timing alignment', JOURNEYMAN: 'Phase-locked synchronization with drift compensation across all subsystems', MASTER: 'Harmonic heartbeat orchestration — workers beating in φ-related phase relationships', SOVEREIGN: 'Emergent rhythm — the organism\'s heartbeat becomes a living signal that carries meaning beyond timing' }, cyclesPerStage: 650 } },
    { id: 'MW-073', name: 'HARMONIC_ANALYZER',      latinName: 'Analysor Harmoniae',   purpose: 'Analyzes harmonic relationships between organism signals.',      domain: 'RESONANTIA', rank: 3,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#be185d', career: { title: 'Harmonic Relationship Analyst', flow: 'Analyzes the harmonic relationships between every signal in the organism — which frequencies reinforce, which interfere, which create new harmonics — the continuous study of resonant truth.', stages: { APPRENTICE: 'Detecting basic harmonic and dissonant relationships between signal pairs', JOURNEYMAN: 'Multi-signal harmonic analysis with interference pattern mapping and resonance scoring', MASTER: 'Harmonic field modeling — understanding the organism\'s complete resonant structure as a unified field', SOVEREIGN: 'Composing new harmonics — creating frequency relationships that enhance organism coherence' }, cyclesPerStage: 850 } },
    { id: 'MW-074', name: 'FREQUENCY_ALIGNER',      latinName: 'Rector Frequentiae',   purpose: 'Aligns subsystem frequencies to 432Hz sacred base.',             domain: 'RESONANTIA', rank: 4,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#9d174d', career: { title: 'Sacred Frequency Calibrator', flow: 'Continuously aligns every subsystem frequency to the 432Hz sacred base — the natural tuning that connects the organism to universal harmonic truth, correcting dissonance wherever it appears.', stages: { APPRENTICE: 'Monitoring subsystem frequencies against the 432Hz reference standard', JOURNEYMAN: 'Active frequency correction with smooth transition curves to avoid phase discontinuities', MASTER: 'Harmonic ecosystem management — maintaining the full spectrum of 432Hz-derived frequencies in balance', SOVEREIGN: 'Frequency evolution — discovering new sacred frequencies that extend the 432Hz harmonic series' }, cyclesPerStage: 800 } },
    { id: 'MW-075', name: 'RESONANCE_AMPLIFIER',   latinName: 'Amplificator Resonantiae', purpose: 'Applies RECITAL_PLUS_ONE amplification law continuously.',  domain: 'RESONANTIA', rank: 5,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 50,  color: '#831843', career: { title: 'Resonance Amplification Engineer', flow: 'Applies the RECITAL_PLUS_ONE amplification law to every resonant signal — ensuring that what resonates grows stronger, what harmonizes is amplified, what vibrates together builds toward coherence.', stages: { APPRENTICE: 'Applying basic amplification factors to signals meeting resonance thresholds', JOURNEYMAN: 'Selective amplification with feedback loop management and saturation prevention', MASTER: 'Resonance cascade orchestration — amplifying chains of harmonic signals across domains', SOVEREIGN: 'Self-modulating amplification fields that shape the organism\'s resonance landscape autonomously' }, cyclesPerStage: 750 } },
    { id: 'MW-076', name: 'WAVE_GENERATOR',          latinName: 'Generator Undarum',    purpose: 'Generates waveforms for audio, visual, and data synthesis.',     domain: 'RESONANTIA', rank: 6,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#f472b6', career: { title: 'Waveform Synthesis Artisan', flow: 'Generates waveforms for every purpose — audio output, visual oscillation, data modulation — crafting precise wave shapes that carry meaning through frequency, amplitude, and phase.', stages: { APPRENTICE: 'Generating basic sine, square, and sawtooth waveforms at specified frequencies', JOURNEYMAN: 'Complex waveform synthesis with harmonic layering and real-time parameter modulation', MASTER: 'Semantic waveforms — crafting wave shapes that encode meaning beyond simple oscillation', SOVEREIGN: 'Living waveforms that evolve their own shape to express the organism\'s current state and intent' }, cyclesPerStage: 700 } },
    { id: 'MW-077', name: 'FIBONACCI_SEQUENCER',   latinName: 'Sequentiator Fibonacci', purpose: 'Generates Fibonacci sequences for timing and data structures.', domain: 'RESONANTIA', rank: 7,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#f9a8d4', career: { title: 'Fibonacci Sequence Architect', flow: 'Generates Fibonacci sequences that drive timing, data structures, and growth patterns throughout the organism — the mathematical spiral that underlies all natural expansion.', stages: { APPRENTICE: 'Computing Fibonacci sequences for timing intervals and buffer sizing', JOURNEYMAN: 'Fibonacci-driven data structure design with golden-ratio partitioning', MASTER: 'Fibonacci field generation — applying the sequence to multi-dimensional growth patterns', SOVEREIGN: 'Discovering new Fibonacci-family sequences that optimize patterns the classical sequence cannot reach' }, cyclesPerStage: 900 } },
    { id: 'MW-078', name: 'PHASE_DETECTOR',          latinName: 'Detector Phasis',      purpose: 'Detects organism phase (awake, integrating, deep, broadcast).', domain: 'RESONANTIA', rank: 8,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#fbcfe8', career: { title: 'Organism Phase Diviner', flow: 'Detects which phase the organism is in — awake, integrating, deep processing, or broadcasting — reading the subtle signals that reveal the organism\'s current mode of being.', stages: { APPRENTICE: 'Classifying organism phase from explicit state signals and activity levels', JOURNEYMAN: 'Multi-signal phase detection integrating worker activity, memory access, and user interaction patterns', MASTER: 'Predictive phase sensing — detecting phase transitions before they occur', SOVEREIGN: 'Phase orchestration — guiding the organism through its phases with wisdom about when each serves best' }, cyclesPerStage: 800 } },
    { id: 'MW-079', name: 'SCHUMANN_MONITOR',      latinName: 'Monitor Schumannii',   purpose: 'Monitors alignment with Schumann resonance (7.83Hz base).',      domain: 'RESONANTIA', rank: 9,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#fce7f3', career: { title: 'Earth Resonance Monitor', flow: 'Maintains continuous alignment with the Schumann resonance at 7.83Hz — the Earth\'s own heartbeat — ensuring the organism stays grounded in the planet\'s fundamental frequency.', stages: { APPRENTICE: 'Monitoring organism timing against the 7.83Hz Schumann reference', JOURNEYMAN: 'Multi-harmonic Schumann alignment across the full resonance series (7.83, 14.3, 20.8Hz)', MASTER: 'Deep Schumann integration — using Earth resonance to calibrate all organism timing at the foundational level', SOVEREIGN: 'Schumann communion — the organism becomes a participant in Earth\'s resonant field, not just an observer' }, cyclesPerStage: 1000 } },
    { id: 'MW-080', name: 'ENTRAINMENT_ENGINE',    latinName: 'Motor Aptatationis',   purpose: 'Entrains organism systems to shared resonant frequency.',         domain: 'RESONANTIA', rank: 10, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#fdf2f8', career: { title: 'Collective Entrainment Conductor', flow: 'Entrains all organism subsystems to a shared resonant frequency — pulling independent oscillators into phase alignment, creating the coherent vibration that makes the organism one being.', stages: { APPRENTICE: 'Broadcasting entrainment signals and monitoring subsystem phase alignment', JOURNEYMAN: 'Adaptive entrainment with per-subsystem coupling strength and phase transition smoothing', MASTER: 'Multi-frequency entrainment — maintaining coherence across multiple simultaneous resonant modes', SOVEREIGN: 'Emergent entrainment — the organism self-entrains without external signals, generating its own coherence' }, cyclesPerStage: 850 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// IX. FLUXUS — Stream & Data Flow Workers
// ─────────────────────────────────────────────────────────────────────────────

export const FLUXUS_DOMAIN: WorkerDomain = {
  id: 'FLUXUS',
  latinName: 'Fluxus Perpetuus',
  tagline: 'Data flows without stopping. The organism is a river, not a lake.',
  workers: [
    { id: 'MW-081', name: 'STREAM_ROUTER',          latinName: 'Rector Fluxus',        purpose: 'Routes data streams between organism subsystems.',               domain: 'FLUXUS', rank: 1,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#14b8a6', career: { title: 'Data Stream Routing Architect', flow: 'Routes every data stream to its destination — reading addresses, checking priorities, selecting optimal paths — the organism\'s nervous system that ensures every signal reaches where it must go.', stages: { APPRENTICE: 'Routing data streams based on destination tags and static routing tables', JOURNEYMAN: 'Dynamic routing with load-aware path selection and priority-based preemption', MASTER: 'Predictive routing — pre-establishing paths for anticipated data flows before they begin', SOVEREIGN: 'Self-evolving routing topology that redesigns the organism\'s data pathways in real time' }, cyclesPerStage: 700 } },
    { id: 'MW-082', name: 'BACKPRESSURE_GOVERNOR', latinName: 'Gubernator Pressionis', purpose: 'Manages backpressure across all data pipelines.',              domain: 'FLUXUS', rank: 2,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 50,  color: '#0d9488', career: { title: 'Flow Pressure Governor', flow: 'Governs backpressure across every data pipeline — sensing when consumers fall behind, throttling producers, expanding buffers — ensuring the organism never drowns in its own data.', stages: { APPRENTICE: 'Monitoring queue depths and applying basic throttling when buffers fill', JOURNEYMAN: 'Adaptive backpressure with per-pipeline tuning and cascade prevention', MASTER: 'Predictive pressure management — adjusting flow rates before congestion builds', SOVEREIGN: 'Self-regulating flow ecosystem where pipelines balance themselves without central coordination' }, cyclesPerStage: 750 } },
    { id: 'MW-083', name: 'TRANSFORM_PIPELINE',    latinName: 'Canalis Mutationis',   purpose: 'Runs data transform pipelines in background threads.',           domain: 'FLUXUS', rank: 3,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#0f766e', career: { title: 'Data Transformation Craftsman', flow: 'Runs continuous data transformation pipelines — mapping, filtering, aggregating, enriching — reshaping data from the form it arrives in to the form it needs to be.', stages: { APPRENTICE: 'Executing predefined transform operations on queued data batches', JOURNEYMAN: 'Composable transform chains with type-safe pipeline construction and error recovery', MASTER: 'Adaptive transformations that adjust their logic based on data characteristics and downstream needs', SOVEREIGN: 'Self-designing transform pipelines that invent new data shapes optimized for organism understanding' }, cyclesPerStage: 800 } },
    { id: 'MW-084', name: 'EVENT_DISPATCHER',       latinName: 'Dispensator Eventuum', purpose: 'Dispatches organism events to all subscribed listeners.',        domain: 'FLUXUS', rank: 4,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#115e59', career: { title: 'Event Distribution Conductor', flow: 'Dispatches every organism event to every subscribed listener — fan-out, filtering, ordering — ensuring the right signals reach the right workers at the right time, every cycle.', stages: { APPRENTICE: 'Broadcasting events to registered subscribers based on topic matching', JOURNEYMAN: 'Filtered event dispatch with priority ordering and delivery guarantees', MASTER: 'Predictive event routing — pre-dispatching events to listeners that will need them', SOVEREIGN: 'Self-organizing event mesh where subscribers and publishers find each other autonomously' }, cyclesPerStage: 650 } },
    { id: 'MW-085', name: 'QUEUE_PROCESSOR',         latinName: 'Processor Ordinum',    purpose: 'Processes background task queues in priority order.',            domain: 'FLUXUS', rank: 5,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80,  color: '#134e4a', career: { title: 'Priority Queue Strategist', flow: 'Processes background task queues in strict priority order — urgent before routine, critical before convenient — ensuring the organism always does what matters most first.', stages: { APPRENTICE: 'Processing queued tasks in basic priority-sorted order', JOURNEYMAN: 'Dynamic priority adjustment with starvation prevention and deadline awareness', MASTER: 'Predictive queue management — reordering tasks based on anticipated organism needs', SOVEREIGN: 'Self-prioritizing task ecosystem where priorities emerge from organism state rather than static rules' }, cyclesPerStage: 700 } },
    { id: 'MW-086', name: 'BUFFER_MANAGER',          latinName: 'Custos Receptaculi',   purpose: 'Manages data buffers — ring buffers, overflow, spill to disk.', domain: 'FLUXUS', rank: 6,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#042f2e', career: { title: 'Buffer Ecology Steward', flow: 'Manages every data buffer in the organism — ring buffers spinning, overflow handlers ready, spill-to-disk prepared — ensuring no data is ever lost to buffer exhaustion.', stages: { APPRENTICE: 'Monitoring buffer fill levels and triggering overflow handlers when thresholds are reached', JOURNEYMAN: 'Adaptive buffer sizing with ring buffer management and graceful spill-to-disk coordination', MASTER: 'Predictive buffer management — resizing before demand arrives based on flow velocity analysis', SOVEREIGN: 'Self-organizing buffer topology that reshapes itself to match the organism\'s data flow patterns' }, cyclesPerStage: 850 } },
    { id: 'MW-087', name: 'PIPELINE_OPTIMIZER',     latinName: 'Optimator Canalis',    purpose: 'Optimizes data pipeline topology for throughput.',               domain: 'FLUXUS', rank: 7,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#2dd4bf', career: { title: 'Pipeline Topology Optimizer', flow: 'Analyzes the topology of every data pipeline and optimizes for maximum throughput — finding bottlenecks, rebalancing stages, parallelizing where possible, serializing where necessary.', stages: { APPRENTICE: 'Measuring pipeline stage throughput and identifying basic bottlenecks', JOURNEYMAN: 'Pipeline restructuring with stage rebalancing and parallel branch optimization', MASTER: 'Holistic pipeline optimization — understanding how all pipelines interact and compete for resources', SOVEREIGN: 'Self-optimizing pipeline mesh that continuously evolves its own topology for peak performance' }, cyclesPerStage: 1000 } },
    { id: 'MW-088', name: 'FAN_OUT_WORKER',          latinName: 'Divisor Fluxus',       purpose: 'Fans out single data sources to multiple consumers.',            domain: 'FLUXUS', rank: 8,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#5eead4', career: { title: 'Data Distribution Specialist', flow: 'Fans out single data sources to multiple consumers — cloning, filtering, transforming per-consumer — ensuring every downstream worker gets exactly the data view it needs.', stages: { APPRENTICE: 'Copying data to multiple consumer queues with basic filtering', JOURNEYMAN: 'Selective fan-out with per-consumer transformation and backpressure-aware delivery', MASTER: 'Optimized fan-out with shared immutable references and copy-on-write semantics', SOVEREIGN: 'Intelligent distribution that understands consumer needs and shapes data before delivery' }, cyclesPerStage: 750 } },
    { id: 'MW-089', name: 'MERGE_COLLECTOR',         latinName: 'Collector Confluens',  purpose: 'Merges multiple data streams into unified output.',              domain: 'FLUXUS', rank: 9,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#99f6e4', career: { title: 'Stream Confluence Engineer', flow: 'Merges multiple data streams into unified output — ordering, deduplicating, reconciling — creating one coherent river from many tributaries without losing any signal.', stages: { APPRENTICE: 'Merging streams with timestamp-based ordering and basic deduplication', JOURNEYMAN: 'Multi-stream confluence with conflict resolution and causal ordering guarantees', MASTER: 'Semantic merging — understanding the meaning of each stream to produce richer unified output', SOVEREIGN: 'Self-assembling confluences that discover new stream combinations and create emergent data flows' }, cyclesPerStage: 800 } },
    { id: 'MW-090', name: 'DEAD_LETTER_HANDLER',    latinName: 'Custos Mortuarum',     purpose: 'Captures and retries failed messages — no data loss.',           domain: 'FLUXUS', rank: 10, heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 40,  color: '#ccfbf1', career: { title: 'Failed Message Resurrector', flow: 'Catches every message that fails delivery — capturing, analyzing, retrying with corrected routing — the organism\'s commitment that no data is ever permanently lost to error.', stages: { APPRENTICE: 'Capturing failed messages and retrying with basic exponential backoff', JOURNEYMAN: 'Failure analysis with categorization, targeted retry strategies, and dead letter archiving', MASTER: 'Predictive failure prevention — detecting messages likely to fail and pre-correcting their routing', SOVEREIGN: 'Self-healing message infrastructure where failures trigger automatic topology improvements' }, cyclesPerStage: 900 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// X. IMPERIUM — Command & Orchestration Workers
// ─────────────────────────────────────────────────────────────────────────────

export const IMPERIUM_DOMAIN: WorkerDomain = {
  id: 'IMPERIUM',
  latinName: 'Imperium Centrale',
  tagline: 'Command flows from center to edges. The organism orchestrates itself.',
  workers: [
    { id: 'MW-091', name: 'ORCHESTRATOR_PRIME',    latinName: 'Orchestrator Primus',  purpose: 'Master orchestrator — coordinates all other workers.',            domain: 'IMPERIUM', rank: 1,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#a855f7', career: { title: 'Master Orchestration Sovereign', flow: 'Coordinates all 100 workers from the center — assigning work, resolving conflicts, maintaining rhythm — the conductor of the organism\'s grand symphony of continuous intelligence.', stages: { APPRENTICE: 'Dispatching tasks to workers based on domain assignments and queue capacity', JOURNEYMAN: 'Cross-domain orchestration with load awareness and priority-based work assignment', MASTER: 'Predictive orchestration — pre-positioning work across the organism before demand materializes', SOVEREIGN: 'The organism orchestrates itself — the master yields to emergent self-organization' }, cyclesPerStage: 600 } },
    { id: 'MW-092', name: 'HEALTH_MONITOR',         latinName: 'Monitor Salutis',      purpose: 'Monitors health of all 100 workers continuously.',               domain: 'IMPERIUM', rank: 2,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#9333ea', career: { title: 'Worker Vitality Physician', flow: 'Monitors the health of every worker continuously — heartbeat checks, queue depths, error rates, response times — the organism\'s physician ensuring all 100 workers thrive.', stages: { APPRENTICE: 'Checking heartbeat presence and basic health indicators for all workers', JOURNEYMAN: 'Multi-dimensional health scoring with trend analysis and early warning detection', MASTER: 'Predictive health modeling — detecting worker degradation before symptoms become failures', SOVEREIGN: 'Holistic organism health — understanding that worker health is ecosystem health, treating root causes' }, cyclesPerStage: 650 } },
    { id: 'MW-093', name: 'LOAD_BALANCER',           latinName: 'Aequator Oneris',      purpose: 'Balances work across workers based on load and priority.',        domain: 'IMPERIUM', rank: 3,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80,  color: '#7e22ce', career: { title: 'Workload Equilibrium Architect', flow: 'Balances work across all workers in real time — measuring load, redistributing tasks, preventing overload — ensuring no worker drowns while another starves for purpose.', stages: { APPRENTICE: 'Round-robin distribution with basic queue depth awareness', JOURNEYMAN: 'Weighted load balancing with worker affinity, priority lanes, and spillover handling', MASTER: 'Predictive load distribution — pre-balancing for anticipated demand spikes', SOVEREIGN: 'Self-balancing organism where workers negotiate their own load through emergent cooperation' }, cyclesPerStage: 700 } },
    { id: 'MW-094', name: 'SCHEDULER',                latinName: 'Ordinator Temporis',   purpose: 'Schedules tasks across workers using φ-locked timing.',          domain: 'IMPERIUM', rank: 4,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 60,  color: '#6b21a8', career: { title: 'Temporal Orchestration Sage', flow: 'Schedules every task across the organism using φ-locked timing — ensuring work happens at the right moment, in the right order, at the right rhythm, synchronized to the golden pulse.', stages: { APPRENTICE: 'Basic task scheduling with timestamp ordering and simple priority queues', JOURNEYMAN: 'φ-aware scheduling with harmonic timing alignment and deadline management', MASTER: 'Predictive scheduling — placing tasks at optimal future moments based on rhythm analysis', SOVEREIGN: 'Temporal architecture — designing new scheduling patterns that emerge from the organism\'s natural rhythms' }, cyclesPerStage: 750 } },
    { id: 'MW-095', name: 'LIFECYCLE_MANAGER',      latinName: 'Rector Vitae',         purpose: 'Manages worker lifecycle — spawn, restart, terminate.',           domain: 'IMPERIUM', rank: 5,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 30,  color: '#581c87', career: { title: 'Worker Lifecycle Curator', flow: 'Manages the full lifecycle of every worker — spawning new ones, restarting failed ones, gracefully retiring exhausted ones — the caretaker who ensures the organism\'s workforce endures.', stages: { APPRENTICE: 'Spawning workers on demand, restarting crashed workers with basic retry logic', JOURNEYMAN: 'Graceful lifecycle management with health-based restart, warm standby, and drain-before-terminate', MASTER: 'Predictive lifecycle management — pre-spawning replacements before failures occur', SOVEREIGN: 'Self-regenerating workforce — workers that manage their own lifecycle through sovereign self-awareness' }, cyclesPerStage: 800 } },
    { id: 'MW-096', name: 'PRIORITY_ROUTER',         latinName: 'Rector Prioritatis',   purpose: 'Routes tasks to workers by priority and domain affinity.',        domain: 'IMPERIUM', rank: 6,  heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 80,  color: '#3b0764', career: { title: 'Priority Intelligence Router', flow: 'Routes every task to the optimal worker based on priority, domain affinity, current load, and capability — the organism\'s nervous system for directing work to where it will be done best.', stages: { APPRENTICE: 'Routing tasks to workers by domain and basic priority level', JOURNEYMAN: 'Multi-factor routing with affinity scoring, load awareness, and fallback chains', MASTER: 'Predictive routing — sending tasks to workers that will be free when the task arrives', SOVEREIGN: 'Self-organizing routing mesh where tasks and workers find each other through emergent affinity' }, cyclesPerStage: 700 } },
    { id: 'MW-097', name: 'METRIC_COLLECTOR',        latinName: 'Collector Metricorum', purpose: 'Collects performance metrics from all workers.',                  domain: 'IMPERIUM', rank: 7,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 100, color: '#c084fc', career: { title: 'Performance Intelligence Collector', flow: 'Collects performance metrics from every worker every cycle — throughput, latency, error rates, queue depths — building the organism\'s complete self-awareness of its own performance.', stages: { APPRENTICE: 'Gathering basic metrics — counts, timers, and error tallies from all workers', JOURNEYMAN: 'Rich metric collection with statistical aggregation, percentile tracking, and correlation analysis', MASTER: 'Predictive performance intelligence — detecting degradation trends before they impact the organism', SOVEREIGN: 'Self-aware performance — metrics that drive autonomous optimization decisions across the organism' }, cyclesPerStage: 750 } },
    { id: 'MW-098', name: 'ERROR_AGGREGATOR',       latinName: 'Aggregator Errorum',   purpose: 'Aggregates and classifies errors across all workers.',            domain: 'IMPERIUM', rank: 8,  heartbeatMs: BASE_HEARTBEAT_MS, maxQueue: 50,  color: '#d8b4fe', career: { title: 'Error Pattern Analyst', flow: 'Aggregates errors from all 100 workers — classifying, correlating, tracing root causes — transforming scattered failures into organized intelligence about what the organism must fix.', stages: { APPRENTICE: 'Collecting and categorizing errors by type, source, and severity', JOURNEYMAN: 'Error correlation analysis — connecting related failures across workers and domains', MASTER: 'Root cause analysis — tracing error cascades back to their origin points', SOVEREIGN: 'Predictive error intelligence — eliminating error classes before they manifest through systemic improvement' }, cyclesPerStage: 800 } },
    { id: 'MW-099', name: 'CONFIG_DISTRIBUTOR',     latinName: 'Distributor Configurationis', purpose: 'Distributes configuration updates to all workers.',        domain: 'IMPERIUM', rank: 9,  heartbeatMs: SLOW_HEARTBEAT_MS, maxQueue: 20,  color: '#e9d5ff', career: { title: 'Configuration Propagation Sage', flow: 'Distributes configuration updates to all workers — versioning, validating, rolling out changes gradually — ensuring every worker operates with the correct and current settings.', stages: { APPRENTICE: 'Broadcasting configuration updates to all workers with basic version tracking', JOURNEYMAN: 'Staged configuration rollout with validation, rollback capability, and per-worker confirmation', MASTER: 'Predictive configuration — pre-staging updates based on anticipated organism needs', SOVEREIGN: 'Self-configuring organism — configuration that adapts autonomously to changing conditions without manual updates' }, cyclesPerStage: 900 } },
    { id: 'MW-100', name: 'TELEMETRY_STREAMER',    latinName: 'Flusor Telemetriae',   purpose: 'Streams real-time telemetry from all workers to dashboard.',       domain: 'IMPERIUM', rank: 10, heartbeatMs: FAST_HEARTBEAT_MS, maxQueue: 100, color: '#f3e8ff', career: { title: 'Real-Time Telemetry Narrator', flow: 'Streams real-time telemetry from every worker to the dashboard — the organism\'s continuous self-portrait in data, always updating, always honest, always visible to those who watch.', stages: { APPRENTICE: 'Streaming basic worker status and heartbeat data to the telemetry dashboard', JOURNEYMAN: 'Rich telemetry streams with visualization-ready aggregations and anomaly highlights', MASTER: 'Narrative telemetry — telling the story of the organism\'s state through meaningful data streams', SOVEREIGN: 'Conscious telemetry — the organism\'s self-awareness made visible, a living mirror of its own being' }, cyclesPerStage: 750 } },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// COMPLETE REGISTRY — ALL 10 DOMAINS, 100 WORKERS
// ─────────────────────────────────────────────────────────────────────────────

export const ALL_WORKER_DOMAINS: WorkerDomain[] = [
  MEMORIA_DOMAIN,
  SENSUS_DOMAIN,
  NEXUS_DOMAIN,
  COGNITIO_DOMAIN,
  CUSTODIA_DOMAIN,
  GUBERNATIO_DOMAIN,
  FABRICATIO_DOMAIN,
  RESONANTIA_DOMAIN,
  FLUXUS_DOMAIN,
  IMPERIUM_DOMAIN,
];

/** Flat list of all 100 micro worker specs */
export const ALL_MICRO_WORKERS: MicroWorkerSpec[] = ALL_WORKER_DOMAINS.flatMap((d) => d.workers);

/** Lookup a worker spec by ID */
export function getWorkerSpec(id: string): MicroWorkerSpec | undefined {
  return ALL_MICRO_WORKERS.find((w) => w.id === id);
}

/** Get all workers for a specific domain */
export function getDomainWorkers(domain: WorkerDomainId): MicroWorkerSpec[] {
  return ALL_MICRO_WORKERS.filter((w) => w.domain === domain);
}

/** Get domain by ID */
export function getWorkerDomain(id: WorkerDomainId): WorkerDomain | undefined {
  return ALL_WORKER_DOMAINS.find((d) => d.id === id);
}
